# Cars 4 You: Expending Car Evaluations with ML

## 1. Import the needed libraries

In [2]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.feature_selection import RFECV
from sklearn.model_selection import KFold
from sklearn.feature_selection import mutual_info_regression
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
from math import ceil
import numpy as np
import os

## 2. Data importation and integration

In [3]:
train_data = pd.read_csv('project_data/train.csv')
test_data = pd.read_csv('project_data/test.csv')

In [4]:
data= train_data.copy()

## 3. Data exploration and understanding

### Metadata
- *carID*: An attribute that contains an identifier for each car.
- *Brand*: The car’s main brand (e.g. Ford, Toyota).
- *model*: The car model.
- *year*: The year of Registration of the Car.
- *mileage*: The total reported distance travelled by the car (in
 miles).
- *tax*: The amount of road tax (in £) that, in 2020, was
 applicable to the car in question.
- *fuelType*: Type of Fuel used by the car (Diesel, Petrol, Hybrid,
 Electric).
- *mpg*: Average Miles per Gallon.
- *engineSize*: Size of Engine in liters (Cubic Decimeters).
- *paintQuality%*:  The mechanic’s assessment of the cars’ overall paint
 quality and hull integrity (filled by the mechanic
 during evaluation). 
- *previousOwners*: Number of previous registered owners of the vehicle.
- *hasDamage*:  Boolean marker filled by the seller at the time of
 registration stating whether the car is damaged or
 not.
- *price*: The car’s price when purchased by Cars 4 You (in £).

### 3.1. Data Overview

In [5]:
#separate numerical and categorical features 

metric_features = ['year', 'mileage', 'tax', 'mpg',
                    'engineSize', 'paintQuality%', 'previousOwners', 'hasDamage']

non_metric_features= ['Brand','model','transmission','fuelType']

identifier = 'carID'

target = 'price'

### 3.2. Checking Duplicates

### 3.3. Checking Missing Values

### 3.4. Checking Outliers

### 3.5. Checking Distributions

In [6]:
df= pd.DataFrame(data[metric_features])

### 3.5. Checking Categorical Variables

### 3.6. Checking Correlation between Variables

## 4. Data preparation

### 4.1. Set index

In [7]:
# Set index to CarID as each car has its own unique identifier
data.set_index('carID', inplace = True)

### 4.2. Slipt the data into train and validation dataset

#### The Hold Out Method

In [8]:
X = data.drop('price', axis = 1) # In X, the target variable will be removed and the dataset will be used as the training set
y = data['price']  # y corresponds to the target variable

In [9]:
# Splits the dataset

X_train, X_val, y_train, y_val = train_test_split(X,y, test_size = 0.3,  # 30% will be used for validation 
                                                  random_state = 0,      # Ensures the split is always the same every time the code runs
                                                  shuffle = True)        # Shuffles the data before spliting to avoid bias

### 4.3. Changing datatypes

In [10]:
# Rounds the floats and changes them to integers

#year to integer
X_train['year'] = X_train['year'].round().astype('Int32')
X_val['year'] = X_val['year'].round().astype('Int32')

#previousOwners to integer
X_train['previousOwners'] = X_train['previousOwners'].round().astype('Int32')
X_val['previousOwners'] = X_val['previousOwners'].round().astype('Int32')

#hasDamaged to boolean
X_train['hasDamage'] = X_train['hasDamage'].astype('Int8')
X_val['hasDamage'] = X_val['hasDamage'].astype('Int8')

In [11]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53181 entries, 42520 to 15659
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Brand           52128 non-null  object 
 1   model           52136 non-null  object 
 2   year            52130 non-null  Int32  
 3   transmission    52086 non-null  object 
 4   mileage         52157 non-null  float64
 5   fuelType        52160 non-null  object 
 6   tax             47671 non-null  float64
 7   mpg             47683 non-null  float64
 8   engineSize      52118 non-null  float64
 9   paintQuality%   52091 non-null  float64
 10  previousOwners  52090 non-null  Int32  
 11  hasDamage       52087 non-null  Int8   
dtypes: Int32(2), Int8(1), float64(5), object(4)
memory usage: 4.7+ MB


### 4.4. Handling Incoherencies

#### 4.4.1. Categorical Variables 

##### 4.4.1.1. Correcting Spelling Mistakes

In [12]:
#correcting spelling mistakes of 'brand' for X_train and X_val

correct_brand = {
    'VW': ['V', 'vw', 'v', 'W', 'w'],
    'Toyota': ['Toyot', 'TOYOTA', 'oyota', 'toyota', 'OYOTA', 'TOYOT', 'toyot'],
    'Audi': ['udi', 'AUDI', 'audi', 'Aud', 'aud', 'UDI', 'AUD'],
    'Ford': ['FOR', 'ord', 'For', 'FORD', 'ford', 'for', 'or', 'ORD'],
    'BMW': ['MW', 'bmw', 'BM', 'mw'],
    'Skoda': ['koda', 'skoda', 'SKODA', 'Skod', 'kod', 'SKOD', 'KODA', 'skod'],
    'Opel': ['Ope', 'opel', 'pel', 'pe', 'OPEL', 'PEL', 'OPE', 'ope'],
    'Mercedes': ['mercedes', 'Mercede', 'MERCEDES', 'ercedes', 'mercede', 'ERCEDES', 'ercede', 'MERCEDE'],
    'Hyundai': ['yundai', 'Hyunda', 'hyundai', 'HYUNDAI', 'yunda', 'HYUNDA', 'ud', 'hyunda']
}

# Create a reverse lookup dictionary (each incorrect form maps to the correct one)
replacement_dict = {variant: correct for correct, variants in correct_brand.items() for variant in variants}

# Replace incorrect brand names with the correct ones
X_train["Brand"] = X_train["Brand"].replace(replacement_dict)
X_val["Brand"] = X_val["Brand"].replace(replacement_dict)

# Verify the cleaning
print(X_train["Brand"].unique())
print(X_val["Brand"].unique())

['Mercedes' 'Ford' 'Hyundai' 'VW' 'Opel' 'Audi' 'Toyota' 'BMW' nan 'Skoda']
['Mercedes' 'Opel' 'Ford' 'VW' 'Toyota' nan 'BMW' 'Skoda' 'Audi' 'Hyundai']


In [13]:
##correcting spelling mistakes of 'model' for X_train and X_val

correct_model = {
    'Golf': [' GOLF', ' Gol', ' golf', 'golf', ' Golf', ' gol', ' GOL', 'Gol', 'GOLF'],
    'Yaris': [' Yaris', ' YARIS', ' Yari', ' yaris', ' yari', 'Yari', ' YARI', 'yaris', 'YARIS'],
    'Q2': [' q2', ' Q2'],
    '2 Series': [' 2 series', ' 2 serie', '2 Series', ' 2 SERIES', ' 2 Serie', '2 Serie', ' 2 Series'],
    '3 Series': [' 3 Series', ' 3 Serie', ' 3 series', ' 3 SERIES', ' 3 serie', '3 Serie'],
    'A3': [' A3', ' a3'],
    'Octavia': [' Octavi', ' OCTAVIA', ' Octavia', ' octavia', 'Octavi', 'octavia', ' octavi', ' OCTAVI'],
    'Passat': [' PASSAT', ' passat', ' Passa', 'Passat', ' Passat', 'PASSAT', ' PASSA'],
    'Insignia': [' Insigni', ' INSIGNIA', ' insignia', ' Insignia', ' INSIGNI', 'Insigni'],
    'Fabia': [' Fabia', ' fabia', ' FABIA', ' Fabi', 'FABIA'],
    'A Class': [' A Clas', ' A Class', ' a class', ' A CLASS', 'a class', 'A CLASS', ' a clas'],
    'Ka+': [' Ka+', ' KA+', ' ka+', 'ka+'],
    'GLC Class': [' GLC Class', ' GLC CLASS', ' GLC Clas', ' glc class', ' glc clas'], 
    'I30': [' i30', ' I30'],
    'C Class': [' C Clas', ' C CLASS', ' c class', 'C Clas', ' C CLAS', 'c class', ' c clas', ' C Class', 'C CLASS'],
    'Polo': [' POLO', ' Polo', ' polo', ' Pol', ' POL', 'Pol', 'POLO'],
    'E Class': [' E Class', ' E Clas', ' E CLASS', ' e class', 'E CLASS', 'e class'],
    'Q5': [' Q5', ' q5', 'q5'],
    'Up': ['U', ' up', ' UP', ' Up', ' U', 'UP'],
    'Fiesta': [' FIESTA', ' fiesta', ' Fiest', ' Fiesta', 'fiesta', 'Fiest', ' FIESTA', 'FIESTA', ' fiest'],
    'C-HR': [' C-H', ' c-hr', ' C-HR', ' c-h'],
    'Mokka X': [' mokka x', ' MOKKA X', ' Mokka X'],
    'Corsa': [' Corsa', ' corsa', ' Cors', ' CORSA', ' cors', ' CORS', 'corsa'],
    'Astra': [' ASTRA', ' Astr', ' Astra', ' astra', 'ASTRA', 'astra'],
    'TT': [' tt', ' TT', ' T'],
    '5 Series': [' 5 Series', ' 5 Serie', ' 5 SERIES', ' 5 series', '5 SERIES', ' 5 SERIE'],
    'Aygo': [' aygo', ' ayg', ' AYGO', ' Ayg', ' Aygo', 'aygo', ' AYG'],
    '4 Series': [' 4 SERIES', ' 4 Serie', ' 4 serie', '4 series', '4 Series', ' 4 Series', ' 4 series'],
    'SLK': [' slk', ' SLK'],
    'Viva': [' viva', ' Viva', ' VIVA', ' Viv', 'viva'],
    'Focus': [' Focus', ' Focu', ' FOCUS', ' focus', ' FOCU', 'focus', 'Focu', ' focu', 'FOCUS'],
    'EcoSport': [' EcoSpor', ' ECOSPORT', ' ecosport', ' EcoSport'],
    'X-CLASS': [' x-clas', ' X-CLAS', ' x-class', ' X-CLASS'],
    'CL Class': [' cl class', ' CL Clas', ' CL CLASS', ' CL Class'],
    'IX20': [' ix20', ' IX20'],
    'Rapid': [' Rapi', ' rapid', ' Rapid'],
    'Auris': [' Auris', ' AURIS', ' auris', ' Auri'],
    'I20': [' i20', ' I20'],
    'X3': [' x3', ' X3'],
    'A8': [' A8', 'a8'],
    'GLS Class': [' GLS Clas', ' GLS CLASS', ' gls class', ' GLS Class'],
    'B-MAX': [' B-MA', ' B-MAX', 'B-MA', ' b-max'],
    'A4': [' A4', ' a4'],
    'Kona': [' KONA', ' Kon', ' Kona', ' KON', ' kona'],
    'I10': [' i10', ' I10'],
    'A1': [' A1', ' a1'],
    'Mokka': [' Mokka ', ' Mokk', ' Mokka', ' mokka ', ' mokka', ' MOKKA', 'Mokka ', 'Mokk'],
    'S-MAX': [' S-MA', ' s-max', ' S-MAX', ' s-ma'],
    'X2': [' x2', ' X2'],
    'Crossland X': [' crossland x', ' CROSSLAND X', ' Crossland X'],
    'Tiguan': [' Tiguan', ' tiguan', ' Tigua', ' TIGUAN', ' TIGUA', 'Tigua', 'TIGUAN', 'tiguan', ' tigua'],
    'A5': [' A5', ' a5', 'a5'],
    'GLE Class': [' GLE Clas', ' GLE Class', ' gle class', ' GLE CLASS'],
    'Zafira': [' Zafira', ' Zafir', ' ZAFIRA', ' zafira', 'Zafir', ' ZAFIR'],
    'Ioniq': [' Ioni', ' Ioniq', ' IONIQ', 'IONIQ', ' ioniq'],
    'A6': [' A6', ' a6'],
    'Yeti Outdoor': [' yeti outdoor', ' Yeti Outdoor', ' YETI OUTDOOR', ' Yeti Outdoo', ' yeti outdoor', 'yeti outdoor', ' yeti outdoo'],
    'X1': [' x1', 'x1', ' X1'],
    'Scala': [' SCALA', ' Scala', ' scala', ' Scal', ' scal'],
    'S Class': [' S Class', ' S Clas', ' s class', ' S CLASS'],
    '1 Series': [' 1 Series', ' 1 SERIES', ' 1 Serie', ' 1 series', '1 SERIES', ' 1 SERIE', '1 series', ' 1 serie'],
    'Kamiq': [' KAMIQ', ' KAMI', ' kamiq', ' Kamiq'],
    'Kuga': [' Kug', ' KUGA', ' kuga', 'Kuga', ' Kuga', 'kuga'],
    'Tourneo Connect': [' tourneo connect', ' Tourneo Connect'],
    'Q7': [' q7', ' Q7'],
    'GLA Class': [' GLA Class', ' GLA CLASS', ' GLA Clas', ' gla class'],
    'Arteon': [' arteon', ' Arteon', ' Arteon'],
    'SL CLASS': [' SL CLAS', ' SL CLASS', ' sl class', ' SL'],
    'Tucson': [' Tucson', ' TUCSON', ' Tucso', ' tucson', ' TUCSO', 'Tucso'],
    'Santa Fe': [' Santa F', ' santa fe', ' SANTA FE', ' Santa Fe'],
    'Grandland X': [' Grandland X', ' grandland x', ' GRANDLAND X'],
    'RAV4': [' rav4', 'RAV4', 'RAV', ' RAV', 'rav4', ' rav', ' RAV4'],
    'Touran': [' Touran', 'Toura', ' TOURAN', ' touran', ' Toura', ' TOURA'],
    'Citigo': [' Citig', ' citigo', ' Citigo', ' CITIGO', 'CITIGO'],
    'Roomster': [' Roomste', ' Roomster'],
    'Prius': [' PRIUS', ' Prius', 'Prius', ' prius'],
    'Corolla': [' corolla', ' COROLLA', ' Coroll', ' Corolla', 'corolla'],
    'B Class': [' b class', ' B Clas', ' B Class', ' B CLASS', 'b class'],
    'Sharan': [' sharan', ' Shara', ' Sharan', ' SHARAN'],
    'Kodiaq': [' Kodia', ' kodiaq', 'kodiaq', ' KODIAQ', ' Kodiaq'],
    'V Class': [' V Clas', ' V CLASS', ' V Class', ' v class'],
    'Caddy Maxi Life': [' Caddy Maxi Lif', ' Caddy Maxi Life'],
    'Superb': [' Superb', ' Super', ' SUPERB', ' superb', ' super'],
    'T-Roc': [' T-Roc', ' T-RO', ' t-roc', ' T-Ro', ' T-ROC'],
    'Combo Life': [' COMBO LIFE', ' combo life', ' Combo Lif', 'COMBO LIFE', ' Combo Life'],
    'Beetle': [' Beetl', ' Beetle', ' beetle'],
    'Galaxy': [' GALAXY', ' Galax', ' galaxy', ' Galaxy'],
    'M3': [' M3', ' m3'],
    'Gtc': [' gtc', ' GTC', ' gtc', 'gtc', 'GTC'],
    'X4': [' X4', ' x4'],
    'KA': [' Ka', ' ka', ' K', ' KA'],
    'IX35': [' ix35', ' IX35'],
    'Grand Tourneo Connect': [' Grand Tourneo Connec', ' Grand Tourneo Connect'],
    'M4': [' m4', ' M4'],
    'Tourneo Custom': [' tourneo custom', ' Tourneo Custo', ' Tourneo Custom'],
    'Z4': [' Z4', ' z4'],
    'X5': [' X5', ' x5'],
    'Meriva': [' Meriva', ' MERIVA', ' Meriv', ' meriva'],
    'RS6': [' RS6'],
    'Verso': [' VERSO', ' verso', ' Verso', ' Vers'],
    'Touareg': [' Touareg', ' TOUAREG', ' touareg', ' Touare'],
    'Mondeo': [' MONDEO', ' Mondeo', ' mondeo', ' MONDE', ' Monde'],
    'Shuttle': [' shuttle', ' Shuttle', ' SHUTTLE'],
    'CLS Class': [' CLS Class', ' cls class', ' CLS Clas', ' CLS CLASS'], 
    'C-MAX': [' C-MAX', ' c-max', ' C-MA'],
    'Puma': [' puma', ' PUMA', ' Puma', 'Pum', ' Pum'],
    'CLA Class': [' CLA Class', ' CLA CLASS', ' cla class', ' CLA Clas'],
    'I40': [' I40', ' i40'],
    'Q3': [' q3', ' Q3'],
    'Tiguan Allspace': [' TIGUAN ALLSPACE', ' tiguan allspace', ' Tiguan Allspac', ' Tiguan Allspace'],
    '6 Series': [' 6 SERIES', ' 6 series', ' 6 Series', ' 6 Serie'],
    'Caravelle': [' caravelle', ' Caravell', ' Caravelle'],
    'Karoq': [' Karoq', ' karoq', ' KAROQ', ' Karo'],
    'I3': [' i3', 'i3', ' I3'],
    'Grand C-MAX': [' GRAND C-MAX', ' grand c-max', ' Grand C-MA', ' Grand C-MAX'],
    'T-Cross': [' T-Cros', ' T-CROSS', ' T-Cross', ' t-cros', ' t-cross'],
    'A7': [' a7', ' A7'],
    'Golf SV': [' Golf SV', ' golf sv', ' GOLF SV'],
    'A': [' a', ' A'],
    'GT86': [' gt86', ' GT86'],
    'Yeti': [' yeti', ' Yet', ' Yeti', ' YETI'],
    'X': [' x', ' X'],
    'Land Cruiser': [' Land Cruise', ' Land Cruiser', ' land cruiser'],
    'EDGE': [' Edge', ' edge', ' Edg', ' EDGE'],
    'X6': [' X6'],
    'Fusion': [' Fusion', ' fusion'],
    'GL Class': [' GL CLASS', ' gl class', ' GL Class', ' GL Clas'],
    'Scirocco': [' scirocco', ' SCIROCCO', ' Scirocc', ' Scirocco'],
    'Z3': [' Z3'],
    'Hilux': [' hilux', ' Hilux', ' Hilu', ' HILU'],
    'Amarok': [' amarok', ' Amarok', ' Amaro'],
    'CC': [' cc', ' CC'],
    '7 Series': [' 7 Serie', ' 7 SERIES', ' 7 series', ' 7 Series'],
    'Avensis': [' AVENSIS', ' avensis', ' Avensis'],
    'M Class': [' m class', ' M CLASS', ' M Class', ' M Clas', ' M CLAS'],
    'Grandland': [' grandland ', ' Grandland '],
    'Zafira Tourer': [' Zafira Toure', ' ZAFIRA TOURER', ' Zafira Tourer', ' zafira tourer'],
    'R8': [' R8', ' r8'],
    'Mustang': [' mustang', ' Mustang'],
    'Q8': [' Q8'],
    'CLK': [' CLK'],
    'RS3': [' RS3'],
    'Jetta': [' JETTA', ' Jetta', ' jetta', 'Jetta' ],
    'Supra': [' Supra'],
    'X7': [' X7'],
    'SQ7': [' SQ7', ' sq7'],
    'S3': [' s3', ' S3'],
    'Arteon': [' Arteo', 'Arteo', ' ARTEON', ' arteon', ' Arteon'],
    'GLB Class': [' glb class', ' GLB Class'],
    'Adam': [' Ada', ' adam', ' ADAM', ' Adam'],
    'M5': [' M5',' m5'],
    'Golf S': [' golf s', ' Golf S'],
    'Vectra': ['Vectra', ' Vectra', ' VECTRA', 'VECTRA'],
    '8 Series': [' 8 SERIES', ' 8 Serie', ' 8 Series', ' 8 series'],
    'Urban Cruiser': [' Urban Cruise', ' Urban Cruiser'],
    'Fox': ['fox', ' fox', ' Fox'], 
    'Q': [' Q'], 
    'M2': [' M2'], 
    'RS4':[' RS4'], 
    'Veloster': [' Veloster', ' Veloste'],  
    'IQ': [' IQ'], 
    'Agila': [' AGILA', ' Agila'], 
    'I2': [' I2'], 
    'Antara': [' Antara'], 
    'G Class': [' G Class'], 
    'Caddy Life': [' Caddy Life', ' Caddy'],
    'R Class': [' R Class'], 
    'I800': [' I800'],
    'Amica': [' Amica'], 
    'Crossland': [' Crossland '],
    'Proace Verso': [' proace verso', ' PROACE VERSO', 'PROACE VERSO'],
    'Camry': [' Camry', 'Camry', ' Camr'], 
    'Tigra': [' Tigra'], 
    'Eos': [' Eos'], 
    'M': [' M'],
    'California': [' Californi', ' California'], 
    'Ampera': [' Ampera'], 
    'I1': [' I1'], 
    'S5': [' S5'], 
    'CLC Class': [' CLC Class'], 
    'Shara': [' SHARA'], 
    'I8': [' i8', 'i8'], 
    'RS7': [' RS7'], 
    'Transit Tourneo': [' Transit Tourneo'], 
    'I4': [' I4'], 
    'S4':[' S4'], 
    'Terracan': [' Terracan'], 
    'Cascada': [' Cascada'], 
    'S8': [' S8'], 
    'A2':[' A2'], 
    'Vivaro':[' Vivaro'],
    'RS5':[' RS5'],
    'SQ5':[' SQ5'], 
    'Getz':[' Getz'], 
    'M6':[' M6'], 
    'Caddy Maxi': [' Caddy Maxi'], 
    'Z':[' Z'], 
    'Verso-S': [' Verso-S'], 
    'Kadjar': [' Kadjar'], 
    'I80': [' I80'], 
    'Streetka': [' Streetka'],
    'RS': [' RS'], 
    'I': [' i'], 
    'Ranger': [' Ranger'], 
    'IX2': [' IX2'], 
    'Escort': [' Escort'],
    'Accent': [' Accent']
}

# Create a reverse lookup dictionary (each incorrect form maps to the correct one)
replacement_dict = {variant: correct for correct, variants in correct_model.items() for variant in variants}

# Replace incorrect brand names with the correct ones
X_train["model"] = X_train["model"].replace(replacement_dict)
X_val["model"] = X_val["model"].replace(replacement_dict)

# Verify the cleaning
print(X_train["model"].unique())
print(X_val["model"].unique())

['E Class' 'Focus' 'C Class' 'IX20' 'Golf' 'I10' 'T-Cross' 'Corsa' 'A4'
 'Polo' 'Tucson' 'Kuga' 'Corolla' 'Yaris' 'Q3' 'A Class' 'A1' 'A5' 'Q5'
 'GLE Class' '3 Series' 'Fiesta' 'T-Roc' 'Insignia' 'GLC Class' 'X1'
 'Astra' 'Q2' 'Aygo' 'C-MAX' 'Q' '2 Series' 'A3' 'Touran' 'TT' 'Santa Fe'
 'C-HR' 'Superb' 'EDGE' 'S Class' 'CL Class' 'Ka+' 'Octavia' 'Arteon' 'X4'
 'Z4' nan 'EcoSport' 'Yeti Outdoor' 'Meriva' 'I20' 'Hilux' 'X5' 'M4'
 'CLA Class' '1 Series' 'Mokka X' 'Prius' 'X2' '4 Series' 'S4' 'Fabia'
 'Auris' 'Galaxy' 'Citigo' 'A6' 'RAV4' 'Passat' 'Grand C-MAX' 'Adam'
 'GLA Class' 'G Class' 'Zafira' 'Touareg' 'Sharan' 'Mokka' 'Tiguan'
 'Ioniq' 'Q7' 'Viva' 'X3' 'Tiguan Allspace' 'B Class' 'Up' 'Crossland X'
 'CLS Class' 'SLK' 'Kodiaq' 'Mondeo' 'B-MAX' 'Caddy Life' 'SL CLASS' 'A7'
 'A' 'I30' 'Yeti' 'Grandland X' 'Tourneo Custom' 'Antara' 'Avensis' 'X6'
 '5 Series' 'GL Class' 'IX35' 'Kamiq' 'KA' 'Caravelle' 'Karoq' 'Scala'
 'V Class' 'Golf SV' 'Verso' 'Kona' '7 Series' '6 Series' 'SQ7' 'Golf 

In [14]:
##correcting spelling mistakes of 'transmission' for X_train and X_val

correct_transmission = {
    'Semi-Auto': ['Semi-Aut', 'semi-auto', 'emi-Auto', 'SEMI-AUTO', 'SEMI-AUT', 'EMI-AUTO', 'emi-Aut', 'emi-auto', 'semi-aut'],
    'Manual': ['anual', 'manual', 'Manua', 'MANUAL', ' Manual ', 'ANUAL', 'manua', 'anua', 'MANUA', ' manual ', ' MANUAL ', ' Manual', 'Manual ', 'manual '],
    'Automatic': ['AUTOMATIC', 'automatic', 'Automati', 'utomatic', 'UTOMATIC', 'automati', 'AUTOMATI', 'utomati'],
}

# Create a reverse lookup dictionary (each incorrect form maps to the correct one)
replacement_dict = {variant: correct for correct, variants in correct_transmission.items() for variant in variants}

# Replace incorrect brand names with the correct ones
X_train["transmission"] = X_train["transmission"].replace(replacement_dict)
X_val["transmission"] = X_val["transmission"].replace(replacement_dict)

#replacing the 'unknown' and 'other' variable with a missing value
X_train["transmission"] = X_train["transmission"].replace(['unknow','UNKNOWN','nknown','nknow', 'unknown', 'Other'], np.nan)
X_val["transmission"] = X_val["transmission"].replace(['unknow','UNKNOWN','nknown','nknow', 'unknown', 'Other'], np.nan)

# Verify the cleaning
print(X_train["transmission"].unique())
print(X_val["transmission"].unique())

['Semi-Auto' 'Automatic' 'Manual' nan]
['Semi-Auto' 'Manual' nan 'Automatic']


In [15]:
##correcting spelling mistakes of 'fuelType' for X_train and X_val

correct_fuelType = {
    'Petrol': ['etrol', 'petrol', 'PETROL', 'Petro', 'petro', 'ETROL', 'PETRO', 'etro', 'ETRO'],
    'Diesel': ['diesel','iesel','Diese','DIESEL','DIESE','IESEL','iese','diese','IESE'],
    'Hybrid': ['HYBRID','ybri','Hybri','ybrid','hybrid','YBRID','HYBRI'],
    'Other': ['ther','Othe','OTHER','other']
}

# Create a reverse lookup dictionary (each incorrect form maps to the correct one)
replacement_dict = {variant: correct for correct, variants in correct_fuelType.items() for variant in variants}

# Replace incorrect brand names with the correct ones
X_train["fuelType"] = X_train["fuelType"].replace(replacement_dict)
X_val["fuelType"] = X_val["fuelType"].replace(replacement_dict)

#replacing the 'other' variable with a missing value 
X_train["fuelType"] = X_train["fuelType"].replace(['ther','Othe','OTHER','other', 'Other'], np.nan)
X_val["fuelType"] = X_val["fuelType"].replace(['ther','Othe','OTHER','other', 'Other'], np.nan)

# Verify the cleaning
print(X_train["fuelType"].unique())
print(X_val["fuelType"].unique())

['Diesel' 'Petrol' 'Hybrid' nan 'Electric']
['Diesel' 'Petrol' nan 'Hybrid']


##### 4.4.1.2. Check if the Models correspond to the Brand

**Audi**

In [16]:
#Check the models of Audi
audi = X_train[X_train['Brand'].str.lower() == 'audi']
unique_audi_models = sorted(audi['model'].dropna().unique())
unique_audi_models

['A',
 'A1',
 'A2',
 'A3',
 'A4',
 'A5',
 'A6',
 'A7',
 'A8',
 'Q',
 'Q2',
 'Q3',
 'Q5',
 'Q7',
 'Q8',
 'R8',
 'RS',
 'RS3',
 'RS4',
 'RS5',
 'RS6',
 'S3',
 'S4',
 'S8',
 'SQ5',
 'SQ7',
 'TT']

In [17]:
#Check the models of Audi
audi = X_val[X_val['Brand'].str.lower() == 'audi']
unique_audi_models_v = sorted(audi['model'].dropna().unique())
unique_audi_models_v

['A',
 'A1',
 'A3',
 'A4',
 'A5',
 'A6',
 'A7',
 'A8',
 'Q',
 'Q2',
 'Q3',
 'Q5',
 'Q7',
 'Q8',
 'R8',
 'RS3',
 'RS4',
 'RS5',
 'RS6',
 'S3',
 'S4',
 'S5',
 'S8',
 'SQ5',
 'SQ7',
 'TT']

- All models seem to correspond to Audi cars, except for models 'A' and 'Q'. There are no models in Audi that are named 'A' and 'Q' solely, normally there are followed by a number, for example, 'A1' or 'Q3' as seen in the dataset. 
- Since it might be a problem of data collection, in a way that is missing a number after the letter, we have decided to replace these values by missing values. 

In [18]:
#replacing model 'A' by missing values
X_train.loc[X_train["model"] == 'A', "model"] = np.nan
X_val.loc[X_val["model"] == 'A', "model"] = np.nan

In [19]:
#replacing model 'Q' by missing values
X_train.loc[X_train["model"] == 'Q', "model"] = np.nan
X_val.loc[X_val["model"] == 'Q', "model"] = np.nan

**BMW**

In [20]:
#Check the models of 'BMW'
BMW = X_train[X_train['Brand'].str.lower() == 'bmw']
unique_bmw_models = sorted(BMW['model'].dropna().unique())
unique_bmw_models

['1 Series',
 '2 Series',
 '3 Series',
 '4 Series',
 '5 Series',
 '6 Series',
 '7 Series',
 '8 Series',
 'I',
 'I3',
 'I8',
 'M',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'X',
 'X1',
 'X2',
 'X3',
 'X4',
 'X5',
 'X6',
 'X7',
 'Z',
 'Z3',
 'Z4']

In [21]:
#Check the models of 'BMW'
BMW = X_val[X_val['Brand'].str.lower() == 'bmw']
unique_bmw_models_v = sorted(BMW['model'].dropna().unique())
unique_bmw_models_v

['1 Series',
 '2 Series',
 '3 Series',
 '4 Series',
 '5 Series',
 '6 Series',
 '7 Series',
 '8 Series',
 'I3',
 'I8',
 'M',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'X',
 'X1',
 'X2',
 'X3',
 'X4',
 'X5',
 'X6',
 'X7',
 'Z3',
 'Z4']

- Similarly to 'Audi', in 'BMW' there are also models that should be followed by a number, which are 'X', 'Z', 'I' and 'M'.
- Therefore, we are going to replace it by missing values, for the same reason. 

In [22]:
#replacing model 'X' by missing values
X_train.loc[X_train["model"] == 'X', "model"] = np.nan
X_val.loc[X_val["model"] == 'X', "model"] = np.nan

In [23]:
#replacing model 'Z' by missing values
X_train.loc[X_train["model"] == 'Z', "model"] = np.nan

In [24]:
#replacing model 'I' by missing values
X_train.loc[X_train["model"] == 'I', "model"] = np.nan

In [25]:
#replacing model 'M' by missing values
X_train.loc[X_train["model"] == 'M', "model"] = np.nan
X_val.loc[X_val["model"] == 'M', "model"] = np.nan

**Ford**

In [26]:
#Check the models of 'Ford'
Ford = X_train[X_train['Brand'].str.lower() == 'ford']
unique_ford_models = sorted(Ford['model'].dropna().unique())
unique_ford_models

['B-MAX',
 'C-MAX',
 'EDGE',
 'EcoSport',
 'Escort',
 'Fiesta',
 'Focus',
 'Fusion',
 'Galaxy',
 'Grand C-MAX',
 'Grand Tourneo Connect',
 'KA',
 'Ka+',
 'Kuga',
 'Mondeo',
 'Mustang',
 'Puma',
 'Ranger',
 'S-MAX',
 'Streetka',
 'Tourneo Connect',
 'Tourneo Custom']

In [27]:
#Check the models of 'Ford'
Ford = X_val[X_val['Brand'].str.lower() == 'ford']
unique_ford_models_v = sorted(Ford['model'].dropna().unique())
unique_ford_models_v

['B-MAX',
 'C-MAX',
 'EDGE',
 'EcoSport',
 'Fiesta',
 'Focus',
 'Fusion',
 'Galaxy',
 'Grand C-MAX',
 'Grand Tourneo Connect',
 'KA',
 'Ka+',
 'Kuga',
 'Mondeo',
 'Mustang',
 'Puma',
 'S-MAX',
 'Tourneo Connect',
 'Tourneo Custom']

- All the models from the lists correspond to Ford models. 

**Hyundai**

In [28]:
#Check the models of 'Hyundai'
Hyundai = X_train[X_train['Brand'].str.lower() == 'hyundai']
unique_hyundai_models = sorted(Hyundai['model'].dropna().unique())
unique_hyundai_models

['Accent',
 'Getz',
 'I1',
 'I10',
 'I2',
 'I20',
 'I3',
 'I30',
 'I40',
 'I80',
 'I800',
 'IX2',
 'IX20',
 'IX35',
 'Ioniq',
 'Kona',
 'Q7',
 'Santa Fe',
 'Tucson',
 'Veloster']

In [29]:
#Check the models of 'Hyundai'
Hyundai = X_val[X_val['Brand'].str.lower() == 'hyundai']
unique_hyundai_models_v = sorted(Hyundai['model'].dropna().unique())
unique_hyundai_models_v

['Getz',
 'I1',
 'I10',
 'I2',
 'I20',
 'I3',
 'I30',
 'I40',
 'I80',
 'I800',
 'IX2',
 'IX20',
 'IX35',
 'Ioniq',
 'Kona',
 'Q3',
 'Q5',
 'Santa Fe',
 'Terracan',
 'Tucson']

- Models 'Q3', 'Q5', 'Q7' are from 'Audi' not from 'Hyundai'. There are no such models in Hyundai. 
- Here, since the number of observations where the brand is a hyundai and the model is either 'Q3', 'Q5', or 'Q7 is low, it was assumes it was a mistake of the brand name, so the brand was changed from 'Hyundai' to 'Audi'. 

In [30]:
# Replace Hyundai Q3 by Audi Q3
mask_val = (X_val["Brand"] == "Hyundai") & (X_val["model"] == "Q3")
X_val.loc[mask_val, "Brand"] = "Audi"
X_val.loc[mask_val, "model"] = "Q3"

# Replace Hyundai Q5 by Audi Q5
mask_val = (X_val["Brand"] == "Hyundai") & (X_val["model"] == "Q5")
X_val.loc[mask_val, "Brand"] = "Audi"
X_val.loc[mask_val, "model"] = "Q5"

# Replace Hyundai Q7 by Audi Q7
mask_train = (X_train["Brand"] == "Hyundai") & (X_train["model"] == "Q7")
X_train.loc[mask_train, "Brand"] = "Audi"
X_train.loc[mask_train, "model"] = "Q7"

**Mercedes**

In [31]:
#Check the models of 'Mercedes'
Mercedes = X_train[X_train['Brand'].str.lower() == 'mercedes']
unique_mercedes_models = sorted(Mercedes['model'].dropna().unique())
unique_mercedes_models

['230',
 'A Class',
 'B Class',
 'C Class',
 'CL Class',
 'CLA Class',
 'CLC Class',
 'CLK',
 'CLS Class',
 'E Class',
 'G Class',
 'GL Class',
 'GLA Class',
 'GLB Class',
 'GLC Class',
 'GLE Class',
 'GLS Class',
 'M Class',
 'S Class',
 'SL CLASS',
 'SLK',
 'V Class',
 'X-CLASS']

In [32]:
#Check the models of 'Mercedes'
Mercedes = X_val[X_val['Brand'].str.lower() == 'mercedes']
unique_mercedes_models_v = sorted(Mercedes['model'].dropna().unique())
unique_mercedes_models_v

['200',
 '220',
 'A Class',
 'B Class',
 'C Class',
 'CL Class',
 'CLA Class',
 'CLK',
 'CLS Class',
 'E Class',
 'G Class',
 'GL Class',
 'GLA Class',
 'GLB Class',
 'GLC Class',
 'GLE Class',
 'GLS Class',
 'M Class',
 'S Class',
 'SL CLASS',
 'SLK',
 'V Class',
 'X-CLASS']

- In Mercedes, 200, 220, 230 are not complete model names, they refer only to the engine/variant, not the class or body style. 
- Therefore, we have decided to replace them by missing values. 

In [33]:
#replacing model '200' by missing value
X_val.loc[X_val["model"] == '200', "model"] = np.nan

#replacing model '220' by missing value
X_val.loc[X_val["model"] == '220', "model"] = np.nan

#replacing model '230' by missing value
X_train.loc[X_train["model"] == '230', "model"] = np.nan

**Opel**

In [34]:
#Check the models of 'Opel'
Opel = X_train[X_train['Brand'].str.lower() == 'opel']
unique_opel_models = sorted(Opel['model'].dropna().unique())
unique_opel_models

['Adam',
 'Agila',
 'Ampera',
 'Antara',
 'Astra',
 'Cascada',
 'Combo Life',
 'Corsa',
 'Crossland',
 'Crossland X',
 'Grandland',
 'Grandland X',
 'Gtc',
 'Insignia',
 'Kadjar',
 'Meriva',
 'Mokka',
 'Mokka X',
 'Tigra',
 'Vectra',
 'Viva',
 'Vivaro',
 'Zafira',
 'Zafira Tourer']

In [35]:
#Check the models of 'Opel'
Opel = X_val[X_val['Brand'].str.lower() == 'opel']
unique_opel_models_v = sorted(Opel['model'].dropna().unique())
unique_opel_models_v

['Adam',
 'Agila',
 'Antara',
 'Astra',
 'Combo Life',
 'Corsa',
 'Crossland',
 'Crossland X',
 'Grandland',
 'Grandland X',
 'Gtc',
 'Insignia',
 'Kadjar',
 'Meriva',
 'Mokka',
 'Mokka X',
 'Viva',
 'Vivaro',
 'Zafira',
 'Zafira Tourer']

- 'Kadjar' is a 'Renault' model not a 'Opel' model.
- Since the brand 'Renault' is not in our dataset, we have decided to replace this model by missing values. 

In [36]:
#replacing model 'Kadjar' by missing value
X_train.loc[X_train["model"] == 'Kadjar', "model"] = np.nan
X_val.loc[X_val["model"] == 'Kadjar', "model"] = np.nan

**Skoda**

In [37]:
#Check the models of 'Skoda'
Skoda = X_train[X_train['Brand'].str.lower() == 'skoda']
unique_skoda_models = sorted(Skoda['model'].dropna().unique())
unique_skoda_models

['Citigo',
 'Fabia',
 'Kamiq',
 'Karoq',
 'Kodiaq',
 'Octavia',
 'Rapid',
 'Roomster',
 'Scala',
 'Superb',
 'Yeti',
 'Yeti Outdoor']

In [38]:
#Check the models of 'Skoda'
Skoda = X_val[X_val['Brand'].str.lower() == 'skoda']
unique_skoda_models_v = sorted(Skoda['model'].dropna().unique())
unique_skoda_models_v

['Citigo',
 'Fabia',
 'Kamiq',
 'Karoq',
 'Kodiaq',
 'Octavia',
 'Rapid',
 'Roomster',
 'Scala',
 'Superb',
 'Yeti',
 'Yeti Outdoor']

- All the models showed seem to correspond to the brand 'Skoda'.

**VW**

In [39]:
#Check the models of 'VW'
VW = X_train[X_train['Brand'].str.lower() == 'vw']
unique_vw_models = sorted(VW['model'].dropna().unique())
unique_vw_models

['Amarok',
 'Arteon',
 'Beetle',
 'CC',
 'Caddy Life',
 'Caddy Maxi',
 'Caddy Maxi Life',
 'California',
 'Caravelle',
 'Eos',
 'Golf',
 'Golf S',
 'Golf SV',
 'Jetta',
 'Passat',
 'Polo',
 'Scirocco',
 'Sharan',
 'Shuttle',
 'T-Cross',
 'T-Roc',
 'Tiguan',
 'Tiguan Allspace',
 'Touareg',
 'Touran',
 'Up']

In [40]:
#Check the models of 'VW'
VW = X_val[X_val['Brand'].str.lower() == 'vw']
unique_vw_models_v = sorted(VW['model'].dropna().unique())
unique_vw_models_v

['Amarok',
 'Arteon',
 'Beetle',
 'CC',
 'Caddy Life',
 'Caddy Maxi',
 'Caddy Maxi Life',
 'California',
 'Caravelle',
 'Eos',
 'Fox',
 'Golf',
 'Golf S',
 'Golf SV',
 'Jetta',
 'Passat',
 'Polo',
 'Scirocco',
 'Sharan',
 'Shuttle',
 'T-Cross',
 'T-Roc',
 'Tiguan',
 'Tiguan Allspace',
 'Touareg',
 'Touran',
 'Up',
 'polo']

- All the models showed seem to correspond to the brand 'VW'.

#### 4.4.2. Numerical Variables 

##### 4.4.2.1. Correcting variables' incoherent values

**Previous Owners**

In [41]:
#checking negative values for X_train
X_train[X_train['previousOwners'] < 0]['previousOwners']

carID
75498    -2
29008    -2
61598    -2
41596    -2
73060    -2
         ..
66085    -2
63759    -2
75549    -2
59833    -2
65364    -2
Name: previousOwners, Length: 265, dtype: Int32

In [42]:
#checking negative values for X_val 
X_val[X_val['previousOwners'] < 0]['previousOwners']

carID
48893    -2
27263    -2
64618    -2
19970    -2
55427    -2
         ..
75662    -2
31261    -2
50689    -2
52063    -2
49608    -2
Name: previousOwners, Length: 106, dtype: Int32

- The training dataset has 265 cars with negative owners and the validation set has 106, all equal to -2, which is not possible. - Since the mean value of the previousOwners is 1.994580 and the median is 2, we made the assumption that these negative values are spelling mistakes made during the data collection, that added the '-'. Therefore, we decided the change all of the negative values to positive.

In [43]:
#replacing the negative values by their module.
X_train['previousOwners'] = X_train['previousOwners'].replace(-2, 2)
X_val['previousOwners'] = X_val['previousOwners'].replace(-2, 2)

**Milage**

In [44]:
#checking negative observations for X_train 
X_train[X_train['mileage'] < 0]

Brand      model  year transmission       mileage fuelType    tax  \
carID                                                                         
30017      Ford       EDGE  2016    Automatic -42650.453719   Diesel  200.0   
52522    Toyota      Auris  2016          NaN -39765.602338   Hybrid    0.0   
70201        VW      T-Roc  2018       Manual -48190.655673   Petrol  150.0   
43065  Mercedes        SLK  2007          NaN -50755.210230   Petrol  325.0   
30227      Ford     Fiesta  2016    Automatic -42650.453719   Petrol   30.0   
...         ...        ...   ...          ...           ...      ...    ...   
70143        VW  Caravelle  2016       Manual -48190.655673   Diesel  235.0   
75549        VW    Golf SV  2016    Automatic -48190.655673   Petrol   30.0   
24436      Ford     Fiesta  2017       Manual -42650.453719   Petrol  125.0   
52966    Toyota      Yaris  2017    Automatic -39765.602338   Petrol  145.0   
2675       Audi         TT  2019    Semi-Auto -52618.457894   Petrol  145.0   

        mpg  engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                              
30017  47.9         2.0      83.000000               0          0  
52522  70.6         1.8      86.000000               2          0  
70201  53.3         1.5            NaN               2          0  
43065  32.1         1.8      92.000000               4          0  
30227  57.7         1.0      45.000000               1          0  
...     ...         ...            ...             ...        ...  
70143  42.8         2.0       1.769474               4          0  
75549  54.3         1.4      59.000000               2          0  
24436  54.3         1.2      97.000000            <NA>          0  
52966  60.1         1.5      66.000000               2          0  
2675   37.2         NaN      87.000000               4          0  

[247 rows x 12 columns]

In [45]:
#checking negative observations for X_val
X_val[X_val['mileage'] < 0]

Brand    model  year transmission       mileage fuelType    tax  \
carID                                                                       
37025  Mercedes  C Class  2016    Semi-Auto -50755.210230   Diesel   30.0   
47157     Skoda  Octavia  2019       Manual -46497.584838   Petrol  145.0   
6786       Audi       Q7  2019    Semi-Auto -52618.457894   Diesel  150.0   
25030      Ford   Fiesta  2017       Manual -42650.453719   Petrol  145.0   
17015      Ford   Fiesta  2018       Manual -42650.453719   Petrol  145.0   
...         ...      ...   ...          ...           ...      ...    ...   
60678      Opel    Mokka  2016       Manual -42707.564215      NaN  160.0   
72628        VW   Arteon  2020    Semi-Auto -48190.655673   Petrol  150.0   
45883  Mercedes  E Class  2016    Semi-Auto -50755.210230   Diesel  160.0   
12446       BMW       X2  2019    Automatic -58540.574478   Petrol  145.0   
52509    Toyota    Yaris  2018    Automatic -39765.602338   Petrol  145.0   

        mpg  engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                              
37025  64.2         1.6            NaN               0          0  
47157  55.4         1.5           89.0               1          0  
6786   33.6         3.0           43.0               3          0  
25030  65.7         1.0           34.0               4          0  
17015  65.7         1.0           33.0               1          0  
...     ...         ...            ...             ...        ...  
60678  44.8         1.4           60.0               1          0  
72628  32.8         2.0           83.0               1          0  
45883  50.4         3.0           48.0               4          0  
12446  38.7         2.0           59.0               4          0  
52509  60.1         1.5           33.0               0          0  

[122 rows x 12 columns]

- Here we have 247 negative values in the training set and 122 in the validation. 
- Since, it appers that these negative numbers do not have any kind of relationship, we decided to convert them into missing values to fill them in later.

In [46]:
#replacing negative values by missing values 
X_train.loc[X_train["mileage"] < 0, "mileage"] = np.nan
X_val.loc[X_val["mileage"] < 0, "mileage"] = np.nan

**Mpg**

In [47]:
#checking negative observations for X_train 
X_train[X_train['mpg'] < 0]

Brand     model  year transmission  mileage fuelType    tax        mpg  \
carID                                                                          
14662   BMW  4 Series  2019    Automatic    123.0   Diesel  145.0 -43.421768   
13698   BMW  3 Series  2016       Manual  59222.0   Diesel  125.0 -43.421768   
14420   BMW  2 Series  2015    Automatic  38902.0   Petrol  260.0 -43.421768   
11883   BMW  2 Series  2019    Semi-Auto   9531.0   Diesel  150.0 -43.421768   
13134   BMW  1 Series  2016       Manual      NaN   Petrol   30.0 -43.421768   
10078   BMW  6 Series  2019    Semi-Auto  27713.0   Diesel  145.0 -43.421768   
13574   BMW  3 Series  2017    Semi-Auto  25000.0   Diesel   30.0 -43.421768   
12352   BMW        M3  2018    Semi-Auto  12879.0   Petrol  150.0 -43.421768   
8542    NaN  3 Series  2013    Semi-Auto  40900.0   Diesel  145.0 -43.421768   
14603   BMW  2 Series  2015    Semi-Auto  26035.0   Petrol  165.0 -43.421768   
13396   BMW        X1  2019    Semi-Auto   5163.0   Petrol  145.0 -43.421768   
13901   BMW  1 Series  2019          NaN  10927.0   Petrol  150.0 -43.421768   
10653   BMW        I3  2017    Automatic  29851.0   Hybrid    0.0 -43.421768   
8314    BMW  5 Series  2014    Semi-Auto  59317.0   Diesel   30.0 -43.421768   
14767   BMW  5 Series  2019    Semi-Auto  13000.0   Hybrid  140.0 -43.421768   
10972   BMW  5 Series  2020    Semi-Auto     11.0   Hybrid  145.0 -43.421768   
7781    BMW  3 Series  2017       Manual  29968.0   Diesel   30.0 -43.421768   
12026   BMW  2 Series  2018       Manual  19853.0   Diesel  150.0 -43.421768   
14842   BMW        X1  2016       Manual  17531.0   Diesel  125.0 -43.421768   
11181   BMW  1 Series  2019    Semi-Auto  10040.0   Diesel  145.0 -43.421768   
13713   BMW  3 Series  2020    Automatic    100.0   Diesel  145.0 -43.421768   
9202    BMW        X1  2016    Automatic  46968.0   Diesel  125.0 -43.421768   
8094    BMW        X3  2016    Automatic  59692.0   Diesel  145.0 -43.421768   
13073   BMW  3 Series  2015    Automatic  35248.0   Diesel   30.0 -43.421768   
8956    BMW  7 Series  2019    Automatic   8546.0   Diesel  145.0 -43.421768   

       engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                        
14662         2.0           58.0               0          0  
13698         2.0           74.0               1          0  
14420         3.0           33.0               4          0  
11883         2.0           64.0               4          0  
13134         1.5           70.0               2          0  
10078         3.0           47.0               1          0  
13574         2.0           43.0               0          0  
12352         3.0           59.0               1          0  
8542          3.0           88.0            <NA>          0  
14603         2.0           75.0               3          0  
13396         2.0           86.0               1          0  
13901         1.5           78.0               4          0  
10653         0.0           40.0               0          0  
8314          2.0           74.0               4          0  
14767         2.0           62.0               4          0  
10972         2.0           77.0               2          0  
7781          2.0           52.0               1          0  
12026         2.0           96.0               3          0  
14842         2.0           60.0               2          0  
11181         2.0           70.0               3          0  
13713         2.0           49.0               4          0  
9202          2.0           82.0               0          0  
8094          2.0           40.0               4          0  
13073         2.0           96.0               3          0  
8956          3.0           43.0               0          0

In [48]:
#checking negative observations for X_val
X_val[X_val['mpg'] < 0]

Brand     model  year transmission  mileage fuelType         tax  \
carID                                                                    
14934   BMW  3 Series  2019    Automatic   3185.0   Petrol  145.000000   
13723   BMW  5 Series  <NA>    Automatic  34599.0   Diesel   30.000000   
13140   BMW  1 Series  2019    Automatic   6744.0   Petrol  -43.242082   
12400   BMW        X5  2016    Automatic  46126.0   Diesel  200.000000   
13874   BMW  2 Series  2014    Automatic  45868.0   Petrol  145.000000   
11921   BMW  2 Series  2017          NaN  14612.0   Diesel  145.000000   
10214   BMW  3 Series  2014    Automatic  45140.0   Diesel  125.000000   
13855   BMW  3 Series  <NA>    Automatic  27725.0   Diesel  145.000000   
11143   BMW        Z4  2013    Semi-Auto  26356.0   Petrol  200.000000   
14127   BMW  2 Series  2020    Semi-Auto   1118.0   Diesel  145.000000   
8691    BMW  1 Series  2019    Automatic  12839.0   Diesel  145.000000   

             mpg  engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                                   
14934 -43.421768         2.0           97.0               3          0  
13723 -43.421768         2.0           43.0               3          0  
13140 -43.421768         1.5           57.0               3          0  
12400 -43.421768         3.0           77.0               2          0  
13874 -43.421768         2.0           95.0               0          0  
11921 -43.421768         2.0           92.0               2          0  
10214 -43.421768         3.0           77.0               2          0  
13855 -43.421768         2.0           96.0               1          0  
11143 -43.421768         2.0           44.0               4          0  
14127 -43.421768         2.0           37.0               1          0  
8691  -43.421768         2.0           68.0               1          0

- We can observe that negative values are all the same. In the context of the variable 'mpg', it is not normal to have dozens of cars with the exact same number of milles per gallon, since the car's consumption are dependent on a lot of factors such as the driver, the age of the car and the way the car is used. We have also noticed that all of the cars with negative values are BMWs, so it was probably an error related to the brand. 
- Therefore we decided to replace them with missing values to fill them afterwards.

In [49]:
#replacing negative values by missing values 
X_train.loc[X_train["mpg"] < 0, "mpg"] = np.nan
X_val.loc[X_val["mpg"] < 0, "mpg"] = np.nan

In [50]:
#checking the observations in X_train where the car is electric
X_train[X_train['fuelType'] == 'Electric']

Brand   model  year transmission  mileage  fuelType  tax    mpg  \
carID                                                                   
21931  Ford  Mondeo  <NA>    Automatic  24531.0  Electric  0.0   67.3   
12786   NaN      I3  2015    Automatic  29465.0  Electric  0.0  470.8   
64169  Opel  Ampera  2015    Automatic  34461.0  Electric  0.0  235.4   
16306  Ford  Mondeo  2016    Automatic   9396.0  Electric  0.0   67.3   

       engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                        
21931    2.000000           82.0               4          0  
12786    3.822758           67.0               2          0  
64169    1.400000           83.0               1          0  
16306    2.000000           59.0               3          0

In [51]:
#checking the observations in X_val where the car is electric
X_val[X_val['fuelType'] == 'Electric']

Empty DataFrame
Columns: [Brand, model, year, transmission, mileage, fuelType, tax, mpg, engineSize, paintQuality%, previousOwners, hasDamage]
Index: []

- Also it does not make sense for an electric car to have the variable *mpg* since electric cars do not use petrol, so “miles per gallon” is meaningless.
- Therefore, we have decided to replace *mpg* of electric cars by 0.

In [52]:
#setting the mpg of electric cars to 0
X_train.loc[X_train['fuelType'] == 'Electric', 'mpg'] = 0

In [53]:
X_train[X_train['fuelType'] == 'Electric']

Brand   model  year transmission  mileage  fuelType  tax  mpg  \
carID                                                                 
21931  Ford  Mondeo  <NA>    Automatic  24531.0  Electric  0.0  0.0   
12786   NaN      I3  2015    Automatic  29465.0  Electric  0.0  0.0   
64169  Opel  Ampera  2015    Automatic  34461.0  Electric  0.0  0.0   
16306  Ford  Mondeo  2016    Automatic   9396.0  Electric  0.0  0.0   

       engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                        
21931    2.000000           82.0               4          0  
12786    3.822758           67.0               2          0  
64169    1.400000           83.0               1          0  
16306    2.000000           59.0               3          0

**Engine Size**

In [54]:
#checking obervations where mpg is lower than 0.5 for X_train 
X_train[X_train['engineSize'] < 0.5]

Brand    model  year transmission  mileage fuelType         tax  \
carID                                                                       
75544        VW     Golf  2016       Manual  36000.0   Petrol  -49.153541   
8487        BMW       X2  2019       Manual    103.0   Diesel  145.000000   
75852        VW     Polo  2020       Manual   1950.0   Petrol  145.000000   
24308       NaN   Fiesta  2014       Manual  59361.0   Petrol    0.000000   
41091  Mercedes  C Class  2019    Semi-Auto   9693.0   Petrol         NaN   
...         ...      ...   ...          ...      ...      ...         ...   
72432        VW     Polo  2018    Semi-Auto   3103.0   Petrol  145.000000   
5271       Audi       Q3  2019       Manual   3125.0   Petrol  145.000000   
46984       NaN      NaN  2019    Automatic   8326.0   Petrol  145.000000   
16713      Ford    Focus  2019       Manual   7124.0   Petrol         NaN   
75954        VW     Golf  2015       Manual  57226.0   Diesel   20.000000   

        mpg  engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                              
75544  53.3    0.186425           40.0               0          0  
8487   53.3    0.313407           41.0               1          0  
75852  48.7    0.186425           98.0               1          0  
24308  65.7   -0.103493           81.0               1          0  
41091   NaN    0.307074           70.0               3          0  
...     ...         ...            ...             ...        ...  
72432  45.6    0.186425           81.0               2          0  
5271   40.9    0.154529           62.0               0          0  
46984  36.7    0.191462           45.0               6          0  
16713   NaN   -0.103493           96.0               2          0  
75954  67.3    0.186425           54.0               1       <NA>  

[390 rows x 12 columns]

In [55]:
#checking obervations where mpg is lower than 0.5 for X_val 
X_val[X_val['engineSize'] < 0.5]

Brand     model  year transmission  mileage fuelType         tax  \
carID                                                                       
4949      Audi       NaN  2018       Manual  20560.0   Petrol  145.000000   
10470      BMW  5 Series  2019    Semi-Auto   3901.0   Petrol  145.000000   
70650       VW     T-Roc  2019          NaN   2009.0   Petrol  303.148891   
32659  Hyundai      IX35  2015       Manual  23041.0   Diesel  165.000000   
24755     Ford     Focus  2018       Manual  13794.0   Petrol  299.473504   
...        ...       ...   ...          ...      ...      ...         ...   
5468      Audi        A1  2015       Manual  20048.0   Petrol    0.000000   
21985     Ford     Focus  2017       Manual  23000.0   Petrol         NaN   
5664      Audi        A6  2019    Automatic   6498.0   Diesel  145.000000   
11545      BMW  3 Series  2019    Semi-Auto   2754.0   Diesel  150.000000   
34141  Hyundai       I20  2018       Manual   3920.0   Petrol  150.000000   

        mpg  engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                              
4949   67.3    0.154529           83.0               2          0  
10470  46.3    0.313407           76.0               3          0  
70650  39.8    0.000000           80.0               4          0  
32659  51.4    0.000000           47.0               1          0  
24755   NaN   -0.103493           93.0               2          0  
...     ...         ...            ...             ...        ...  
5468   67.3    0.154529           55.0               3          0  
21985   NaN    0.000000           52.0               3          0  
5664   50.4    0.154529           90.0               2          0  
11545  52.3    0.313407           68.0               2          0  
34141  46.3    0.000000           54.0               3          0  

[128 rows x 12 columns]

- The negative values of EngineSize are all equal and they all belong to a ford. However, the model is different. It is not common for these models to have the same engine size, therefore, we have decided to replace by missing values. 
- In addition, we have rows where the value is less than 0.5. In those cases, the numbers are changed to missing values as it is highly unlikely to have cars with engine size smaller than 0.5.

In [56]:
#replacing negative values by missing values 
X_train.loc[X_train["engineSize"] < 0.5, "engineSize"] = np.nan
X_val.loc[X_val["engineSize"] < 0.5, "engineSize"] = np.nan

**Tax**

In [57]:
#checking negative observations for X_train 
X_train[X_train['tax'] < 0]

Brand     model  year transmission  mileage fuelType        tax  \
carID                                                                       
75544        VW      Golf  2016       Manual  36000.0   Petrol -49.153541   
71704        VW    Tiguan  2017       Manual  20000.0   Petrol -49.153541   
1985       Audi        A4  2013    Automatic  81000.0   Diesel -60.684095   
29851      Ford     Focus  2019    Automatic  17476.0   Diesel -45.780610   
50135     Skoda   Octavia  2019       Manual  13901.0   Petrol -18.330743   
...         ...       ...   ...          ...      ...      ...        ...   
10162       BMW  1 Series  2009       Manual  77000.0   Petrol -43.242082   
43348  Mercedes   C Class  2019    Automatic  12986.0   Diesel -56.193202   
42490  Mercedes   C Class  2024    Semi-Auto    901.0   Diesel -56.193202   
54940    Toyota      Aygo  2018       Manual   4346.0   Petrol -91.121630   
4681       Audi        A1  2020       Manual   3265.0   Petrol -60.684095   

             mpg  engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                                   
75544  53.300000         NaN      40.000000               0          0  
71704  48.700000         1.4      50.000000               2          0  
1985   58.900000         2.0     125.301945               3          0  
29851  64.200000         NaN      41.000000               2          0  
50135  55.400000         1.5      73.000000               4          0  
...          ...         ...            ...             ...        ...  
10162  42.800000         2.0      56.000000               3          0  
43348        NaN         2.0      37.000000               1          0  
42490  61.400000         2.0      36.000000               3          0  
54940  68.900000         1.0      49.000000               4          0  
4681    9.821462         1.0      32.000000               1          0  

[254 rows x 12 columns]

In [58]:
#checking negative observations for X_val
X_val[X_val['tax'] < 0]

Brand      model  year transmission  mileage fuelType        tax  \
carID                                                                        
64518      Opel      Corsa  2017       Manual  15388.0   Petrol -20.241079   
10920       BMW   4 Series  <NA>       Manual   3500.0      NaN -43.242082   
68172        VW         Up  2016       Manual  40524.0   Petrol -49.153541   
44618  Mercedes    C Class  2017    Automatic  35649.0   Diesel -56.193202   
7577        BMW   5 Series  2015       Manual  68310.0   Diesel -43.242082   
...         ...        ...   ...          ...      ...      ...        ...   
42420  Mercedes    B Class  2019    Automatic  13866.0   Petrol -56.193202   
46614  Mercedes  GLE Class  2017    Semi-Auto  25542.0   Diesel -56.193202   
13256       BMW   2 Series  2019    Automatic   5913.0   Hybrid -43.242082   
61217      Opel      Astra  2016       Manual  17458.0   Petrol -20.241079   
10292       BMW         X1  2016    Automatic  28785.0   Diesel -43.242082   

         mpg  engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                               
64518   55.4         1.4           51.0               2          0  
10920   46.3         2.0           60.0               2          0  
68172   62.8         1.0           96.0               0          0  
44618    NaN         2.1           68.0               1          0  
7577    65.7         2.0           64.0               2          0  
...      ...         ...            ...             ...        ...  
42420   45.6         1.3           72.0               2          0  
46614   42.8         3.0           61.0               4          0  
13256  148.7         1.5           46.0               0          0  
61217   64.2         1.0           67.0               4          0  
10292   57.6         2.0           97.0               3          0  

[124 rows x 12 columns]

- Even tough 'tax' has different values for different cars, it can never be negative, because that would mean the government is paying the owner to own the car, which is impossible. 
- We have decided to replace these values by missing values. 

In [59]:
#replacing negative values by missing values 
X_train.loc[X_train["tax"] < 0, "tax"] = np.nan
X_val.loc[X_val["tax"] < 0, "tax"] = np.nan

**Paint Quality (%)**

In [60]:
#checking values higher than 100 for X_train 
X_train[X_train['paintQuality%'] > 100]

Brand    model  year transmission  mileage fuelType    tax   mpg  \
carID                                                                        
74665        VW     Polo  2019       Manual   6000.0   Petrol  145.0  52.3   
40692  Mercedes  A Class  2018    Automatic   8804.0   Petrol  145.0  28.5   
11730       BMW       X3  2019    Semi-Auto   8438.0   Petrol  145.0  30.4   
62837      Opel    Corsa  2018       Manual   8988.0   Petrol  145.0  55.4   
347        Audi       Q3  2019    Automatic      NaN   Petrol  145.0  30.7   
...         ...      ...   ...          ...      ...      ...    ...   ...   
44411  Mercedes  E Class  2015    Semi-Auto  40085.0   Diesel  160.0  51.4   
64036      Opel    Astra  2017       Manual  42536.0   Diesel   20.0  72.4   
41266  Mercedes  C Class  2019    Semi-Auto   6225.0   Diesel  145.0  55.4   
40648  Mercedes  A Class  2018    Semi-Auto  23951.0   Petrol  150.0  49.6   
71467        VW   Tiguan  2020       Manual   2000.0   Diesel  145.0  47.9   

       engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                        
74665         1.0     125.366507               2          0  
40692         1.3     125.202033               2          0  
11730         2.0     125.569499               1          0  
62837         1.4     125.003773               2          0  
347           2.0     125.301945               0          0  
...           ...            ...             ...        ...  
44411         2.1     125.202033               4          0  
64036         1.6     125.003773               0          0  
41266         2.0     125.202033               1          0  
40648         1.6     125.202033               1          0  
71467         2.0     125.366507               0          0  

[254 rows x 12 columns]

In [61]:
#checking values higher than 100 for X_val 
X_val[X_val['paintQuality%'] > 100]

Brand      model  year transmission  mileage fuelType    tax   mpg  \
carID                                                                          
9129        BMW        NaN  2024    Semi-Auto  11454.0   Diesel  160.0  51.4   
8703        BMW   4 Series  2017    Automatic  18295.0   Petrol  145.0  48.7   
45011  Mercedes  GLC Class  2018    Semi-Auto   6945.0   Diesel  150.0  56.5   
15890      Ford      Focus  2019       Manual   9550.0   Diesel    NaN   NaN   
54470    Toyota       C-HR  2018    Automatic   9971.0   Hybrid  135.0  74.3   
...         ...        ...   ...          ...      ...      ...    ...   ...   
71202        VW     Tiguan  2013    Semi-Auto  73707.0   Diesel  205.0  47.7   
48677     Skoda      Fabia  2019       Manual  11552.0   Petrol  145.0  61.4   
23143      Ford      Focus  2019       Manual   6953.0   Petrol    NaN   NaN   
25371      Ford      C-MAX  2015       Manual  32465.0   Petrol   30.0  55.4   
49990     Skoda      Fabia  2017       Manual  40000.0   Petrol  145.0  64.2   

       engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                        
9129          3.0     125.569499               1          0  
8703          2.0     125.569499               4          0  
45011         2.1     125.202033               0          0  
15890         1.5     125.109951               3          0  
54470         1.8     125.594308               1          0  
...           ...            ...             ...        ...  
71202         2.0     125.366507               2          0  
48677         1.0     125.453599               3          0  
23143         1.0     125.109951               1          0  
25371         1.0     125.109951               3          0  
49990         1.0     125.453599               0          0  

[113 rows x 12 columns]

- It does not make sense to have higher values than 100, since tax is a percentage.
- Therefore, we have decided to replace them by missing values.

In [62]:
#replacing values higher than 100 by missing values 
X_train.loc[X_train["paintQuality%"] > 100, "paintQuality%"] = np.nan
X_val.loc[X_val["paintQuality%"] > 100, "paintQuality%"] = np.nan

**Year**

In [63]:
#checking values higher than 2020 for X_train 
X_train[X_train['year'] > 2020]

Brand     model  year transmission  mileage fuelType    tax   mpg  \
carID                                                                         
58698      Opel  Insignia  2023       Manual  34850.0   Petrol  125.0  50.4   
32317   Hyundai       I10  2023       Manual  17470.0   Petrol  145.0  57.7   
56901      Opel     Astra  2023       Manual      NaN   Petrol  150.0  62.8   
44150  Mercedes   C Class  2024       Manual  31540.0   Petrol  145.0  49.6   
684        Audi        A1  2024       Manual  24755.0      NaN    0.0  76.3   
...         ...       ...   ...          ...      ...      ...    ...   ...   
3088       Audi        A4  2024    Semi-Auto  31850.0   Petrol  145.0  36.7   
54235    Toyota     Yaris  2023       Manual   2157.0   Petrol  145.0  47.9   
13248       BMW  4 Series  2024       Manual  42348.0   Petrol  200.0  40.4   
42362  Mercedes   A Class  2024    Semi-Auto  23247.0   Petrol  200.0  42.8   
11336       BMW        Z4  2024    Semi-Auto   8004.0   Petrol  145.0  37.2   

       engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                        
58698         1.4           39.0               4          0  
32317         1.2           41.0               3          0  
56901         1.0           89.0               4          0  
44150         2.0           67.0               0          0  
684           1.6           73.0               0          0  
...           ...            ...             ...        ...  
3088          3.0           41.0               1          0  
54235         1.5           71.0               2          0  
13248         2.0           86.0               2          0  
42362         2.0           75.0               2          0  
11336         2.0           67.0               2          0  

[250 rows x 12 columns]

In [64]:
#checking values higher than 2020 for X_val 
X_val[X_val['year'] > 2020]

Brand     model  year transmission  mileage fuelType    tax   mpg  \
carID                                                                         
61654      Opel    Zafira  2023       Manual  14466.0   Petrol  200.0   NaN   
6647       Audi        R8  2024    Semi-Auto   4000.0   Petrol  145.0  21.4   
26145      Ford     Focus  2023       Manual  77000.0   Diesel   20.0  67.3   
60921      Opel       NaN  2023    Automatic  33490.0   Diesel  145.0  51.4   
50094     Skoda   Octavia  2023       Manual  15740.0   Petrol  145.0  58.9   
...         ...       ...   ...          ...      ...      ...    ...   ...   
8195        BMW  2 Series  2024       Manual  43555.0   Petrol   30.0  57.6   
46582  Mercedes   C Class  2024    Semi-Auto  51304.0   Diesel    NaN   NaN   
35087  Mercedes   E Class  2024    Automatic   2553.0   Diesel  145.0  70.6   
71459        VW    Tiguan  2023       Manual   9195.0   Diesel  145.0  47.9   
33600   Hyundai       I20  2023       Manual  16764.0   Petrol  150.0  58.9   

       engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                        
61654         1.4           66.0               3          0  
6647          5.2           95.0               4          0  
26145         1.6           84.0               4          0  
60921         2.0           42.0               4          0  
50094         1.0           68.0               0          0  
...           ...            ...             ...        ...  
8195          1.5           92.0               0          0  
46582         2.1           66.0               4          0  
35087         2.0           74.0               1          0  
71459         2.0           97.0               0          0  
33600         1.2           31.0               1          0  

[108 rows x 12 columns]

- Since the dataset we are analysing is from 2020, it does not make sense to have years after 2020. Noting that the only years that appear in the dataset after 2020 are 2023 and 2024.
- Therefore, we have decided to replace these years by missing values, assumming there was an error in the system. These years could be 2013 and 2014 instead. 

In [65]:
#replacing years after 2020 by missing values 
X_train.loc[X_train["year"] > 2020, "year"] = np.nan
X_val.loc[X_val["year"] > 2020, "year"] = np.nan

### 4.5. Removing Duplicates

In [66]:
#checking duplicates again after handling incoherencies on X_train
int(X_train.duplicated().sum())

8

In [67]:
#checking duplicates again after handling incoherencies on X_val
int(X_val.duplicated().sum())

3

In [68]:
#droping duplicate rows 
X_train = X_train.drop_duplicates()
X_val = X_val.drop_duplicates()

### 4.6. Treating Outliers

**Year**

In [69]:
'''# Cap year: replacing all numbers below 1995 by 1995
df["year"] = df["year"].clip(lower=1995, upper=2020)'''

'# Cap year: replacing all numbers below 1995 by 1995\ndf["year"] = df["year"].clip(lower=1995, upper=2020)'

In [70]:
# Creating a df of observations where year >= 1995
X_train_year= X_train[X_train['year'] >= 1995]
X_val_year= X_val[X_val['year'] >= 1995]

In [71]:
# Checking the percentage of data that would be kept after removing outliers
print('Percentage of data kept after removing outliers:')
print(np.round(X_train_year.shape[0] / X_train.shape[0], 4))
print(np.round(X_val_year.shape[0] / X_val.shape[0], 4))

Percentage of data kept after removing outliers:
0.9755
0.976


In [72]:
# Removing from the datasets
X_train= X_train[X_train['year'] >= 1995]
X_val= X_val[X_val['year'] >= 1995]

**Milage**

In [73]:
X_train[X_train['mileage'] > 150000]

Brand         model  year transmission   mileage fuelType    tax  \
carID                                                                        
58385      Opel         Astra  2008       Manual  186500.0   Petrol  260.0   
45553  Mercedes       C Class  2012    Automatic  170000.0   Diesel  145.0   
7038       Audi            A3  2009       Manual  152034.0   Diesel  150.0   
19562      Ford         Focus  2003       Manual  177644.0   Petrol  200.0   
45795  Mercedes       C Class  2008    Automatic  170000.0   Diesel    NaN   
67297        VW          Golf  2009       Manual  193000.0   Diesel  160.0   
41580  Mercedes       C Class  2012    Automatic  170000.0   Diesel    NaN   
4692       Audi            A6  2008       Manual  323000.0   Diesel  200.0   
12289       BMW      3 Series  2010       Manual  156800.0   Diesel  125.0   
50804     Skoda       Octavia  2015       Manual  175500.0   Diesel    0.0   
67131        VW          Golf  2014       Manual  152420.0   Diesel   20.0   
52908    Toyota       Avensis  2003       Manual  167054.0   Diesel  205.0   
45662  Mercedes           CLK  2003    Automatic  185000.0   Petrol  330.0   
36131  Mercedes       M Class  2004    Semi-Auto  165000.0   Petrol  330.0   
41128  Mercedes       E Class  2014    Automatic  154000.0   Diesel   30.0   
20862      Ford        Mondeo  2015       Manual  150890.0   Diesel   30.0   
69404        VW        Passat  2010       Manual  168000.0   Diesel  125.0   
53134    Toyota  Land Cruiser  2004    Automatic  160000.0   Diesel  325.0   
39946  Mercedes       A Class  2016          NaN  240494.0   Diesel   20.0   
36409  Mercedes       C Class  2007    Automatic  160000.0   Diesel  290.0   
46607  Mercedes       M Class  2010    Automatic  155876.0   Diesel  540.0   

        mpg  engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                              
58385  36.7         1.8           54.0               1          0  
45553  54.3         2.1           64.0               4          0  
7038   55.4         1.9           33.0               4          0  
19562  41.5         1.6           53.0               2          0  
45795   NaN         2.1           67.0               3          0  
67297  52.3         2.0           62.0               3          0  
41580   NaN         2.1           49.0               2          0  
4692   44.1         2.0           74.0               1          0  
12289  58.9         2.0           49.0               4          0  
50804  74.3         1.6           92.0               2          0  
67131  67.3         2.0           78.0               2          0  
52908  48.7         2.0           36.0               4          0  
45662  17.8         4.3           96.0               2          0  
36131  20.0         NaN           93.0               2          0  
41128  58.9         2.1           60.0               2          0  
20862  65.7         2.0           37.0               4          0  
69404  60.1         2.0           56.0               0          0  
53134  31.4         3.0           58.0               1          0  
39946  68.9         2.1           81.0               4          0  
36409  39.2         2.2           32.0               3          0  
46607  32.5         3.0           72.0               0          0

In [74]:
# Cap milage: replacing all numbers above 150000 by 150000
X_train["mileage"] = X_train["mileage"].clip(lower=0, upper=150000)
X_val["mileage"] = X_val["mileage"].clip(lower=0, upper=150000)

In [75]:
'''# Creating a df of observations where milage < 150000
X_train_mil= X_train[X_train['mileage'] < 150000]
X_val_mil= X_val[X_val['mileage'] < 150000]'''

"# Creating a df of observations where milage < 150000\nX_train_mil= X_train[X_train['mileage'] < 150000]\nX_val_mil= X_val[X_val['mileage'] < 150000]"

In [76]:
'''# Checking the percentage of data that would be kept after removing outliers
print('Percentage of data kept after removing outliers:')
print(np.round(X_train_mil.shape[0] / X_train.shape[0], 4))
print(np.round(X_val_mil.shape[0] / X_val.shape[0], 4))'''

"# Checking the percentage of data that would be kept after removing outliers\nprint('Percentage of data kept after removing outliers:')\nprint(np.round(X_train_mil.shape[0] / X_train.shape[0], 4))\nprint(np.round(X_val_mil.shape[0] / X_val.shape[0], 4))"

In [77]:
''' Removing from the datasets
X_train= X_train[X_train['mileage'] < 150000]
X_val= X_val[X_val['mileage'] < 150000]'''

" Removing from the datasets\nX_train= X_train[X_train['mileage'] < 150000]\nX_val= X_val[X_val['mileage'] < 150000]"

**Tax**

In [78]:
X_train[X_train['tax'] < 50]

Brand    model  year transmission  mileage fuelType   tax       mpg  \
carID                                                                         
74356      VW     Golf  2016    Semi-Auto  19432.0   Diesel  30.0  62.80000   
75498      VW     Polo  2016    Semi-Auto   8695.0   Petrol  20.0  60.10000   
51358  Toyota    Yaris  2017    Automatic  32994.0   Petrol  30.0  55.00000   
2043     Audi       A1  2016    Semi-Auto  33435.0   Petrol  30.0  70.60000   
166      Audi       A5  2014       Manual  30884.0   Diesel  30.0  60.10000   
...       ...      ...   ...          ...      ...      ...   ...       ...   
28583    Ford    B-MAX  2013       Manual  37058.0      NaN  30.0  27.70949   
31202    Ford    Focus  2017       Manual  13000.0   Petrol  20.0  61.40000   
2492     Audi       A4  2016    Automatic  28325.0   Diesel   0.0  72.40000   
48672   Skoda  Octavia  2016    Semi-Auto  37296.0   Petrol  30.0  57.70000   
6205     Audi       TT  2016          NaN  28402.0   Diesel  30.0  62.80000   

       engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                        
74356         2.0           69.0               3          0  
75498         1.2           61.0               2          0  
51358         1.3           65.0               2          0  
2043          1.4           49.0               0          0  
166           2.0           68.0               3          0  
...           ...            ...             ...        ...  
28583         1.0           77.0               3          0  
31202         1.0           82.0               4          0  
2492          2.0           48.0               3          0  
48672         1.4           45.0               3          0  
6205          2.0           57.0               3          0  

[10783 rows x 12 columns]

In [79]:
#the same as 400
X_train[X_train['tax'] > 350]

Brand         model  year transmission   mileage fuelType    tax  \
carID                                                                        
41531  Mercedes      SL CLASS  2016    Automatic    6200.0   Petrol  555.0   
44516  Mercedes      SL CLASS  2010    Automatic   79000.0   Petrol  555.0   
54636    Toyota  Land Cruiser  2006    Automatic  113000.0   Diesel  555.0   
37494  Mercedes       M Class  2010    Automatic  128000.0   Diesel  555.0   
52900    Toyota  Land Cruiser  2014    Automatic   60000.0   Diesel  540.0   
...         ...           ...   ...          ...       ...      ...    ...   
2116       Audi           RS6  2014    Automatic   59894.0   Petrol  555.0   
56446      Opel        Antara  2007    Automatic   99500.0   Diesel  565.0   
35606  Mercedes       M Class  2009    Automatic   59000.0   Diesel  555.0   
46607  Mercedes       M Class  2010    Automatic  150000.0   Diesel  540.0   
40610  Mercedes      GL Class  2007    Automatic   74000.0   Diesel  570.0   

        mpg  engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                              
41531  28.0         5.5           79.0               4       <NA>  
44516  29.1         3.5           47.0               4          0  
54636  31.4         3.0           91.0               0          0  
37494  32.5         3.0           64.0               1          0  
52900  29.7         4.5           69.0               1          0  
...     ...         ...            ...             ...        ...  
2116   28.8         NaN           68.0               4          0  
56446  32.8         2.0           87.0               3          0  
35606  30.4         3.0           67.0               2          0  
46607  32.5         3.0           72.0               0          0  
40610  28.8         3.0           96.0               1          0  

[74 rows x 12 columns]

- Since the number of cars with *tax* less tahn 100 is large, these we will not be changed.

In [80]:
# Cap tax: replacing all numbers above 350 by 350
X_train["tax"] = X_train["tax"].clip(lower=0, upper=350)
X_val["tax"] = X_val["tax"].clip(lower=0, upper=350)

In [81]:
'''# Creating a df of observations where tax < 600
X_train_tax= X_train[X_train['tax'] < 600]
X_val_tax= X_val[X_val['tax'] < 600]'''

"# Creating a df of observations where tax < 600\nX_train_tax= X_train[X_train['tax'] < 600]\nX_val_tax= X_val[X_val['tax'] < 600]"

In [82]:
'''# Checking the percentage of data that would be kept after removing outliers
print('Percentage of data kept after removing outliers:')
print(np.round(X_train_tax.shape[0] / X_train.shape[0], 4))
print(np.round(X_val_tax.shape[0] / X_val.shape[0], 4))'''

"# Checking the percentage of data that would be kept after removing outliers\nprint('Percentage of data kept after removing outliers:')\nprint(np.round(X_train_tax.shape[0] / X_train.shape[0], 4))\nprint(np.round(X_val_tax.shape[0] / X_val.shape[0], 4))"

- Since the outliers constitute more than 3% of the data, they will not be removed

**Mpg**

In [83]:
X_train[X_train['mpg'] > 300]

Brand model  year transmission  mileage fuelType    tax    mpg  \
carID                                                                  
11068   BMW    I3  2016          NaN  43695.0   Hybrid    0.0  470.8   
14531   BMW    I3  2017    Automatic  36429.0   Hybrid    0.0  470.8   
12332   BMW    I3  2015    Automatic  65800.0   Hybrid    0.0  470.8   
9643    BMW    I3  2017    Automatic  20929.0   Hybrid  135.0  470.8   
12640   BMW    I3  2017    Automatic  23956.0      NaN  135.0  470.8   
12269   BMW    I3  2017    Automatic  26965.0   Hybrid  140.0  470.8   
13378   BMW    I3  2015    Automatic   9886.0   Hybrid    0.0  470.8   
11962   BMW    I3  2017    Automatic  21025.0   Hybrid    0.0  470.8   
10327   BMW    I3  2014    Automatic  42479.0   Hybrid    0.0  470.8   
11532   BMW    I3  2016    Automatic  35446.0   Hybrid    0.0  470.8   
10695   BMW    I3  2017    Automatic      NaN   Hybrid  135.0  470.8   
14512   BMW   NaN  2017    Automatic  23983.0   Hybrid    0.0  470.8   
9737    BMW    I3  2014    Automatic  34539.0   Hybrid    0.0  470.8   
9815    BMW    I3  2016    Automatic  20013.0      NaN    0.0  470.8   
13430   BMW    I3  2017    Automatic  41146.0   Hybrid    0.0  470.8   
12853   BMW    I3  2017    Automatic  10839.0   Hybrid    0.0  470.8   

       engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                        
11068         NaN           81.0               1          0  
14531         NaN           30.0               2          0  
12332         NaN           50.0               3          0  
9643          NaN           71.0               2          0  
12640         0.6           53.0               1          0  
12269         NaN           81.0               3          0  
13378         NaN           44.0               0          0  
11962         NaN           66.0               0          0  
10327         NaN           79.0               2          0  
11532         NaN           59.0               3          0  
10695         NaN           54.0               1          0  
14512         NaN           95.0               4          0  
9737          NaN           42.0               0          0  
9815          NaN           30.0               0          0  
13430         NaN           69.0               1          0  
12853         NaN           31.0               4          0

- All mpg > 300 are from BMW I3 and they all have the same mpg.

In [84]:
# Cap mpg: replacing all numbers above 300 by 300
X_train["mpg"] = X_train["mpg"].clip(lower=0, upper=300)
X_val["mpg"] = X_val["mpg"].clip(lower=0, upper=300)

In [85]:
'''# Creating a df of observations where mpg < 500
X_train_mpg= X_train[X_train['mpg'] < 500]
X_val_mpg= X_val[X_val['mpg'] < 500]'''

"# Creating a df of observations where mpg < 500\nX_train_mpg= X_train[X_train['mpg'] < 500]\nX_val_mpg= X_val[X_val['mpg'] < 500]"

In [86]:
'''# Checking the percentage of data that would be kept after removing outliers
print('Percentage of data kept after removing outliers:')
print(np.round(X_train_mpg.shape[0] / X_train.shape[0], 4))
print(np.round(X_val_mpg.shape[0] / X_val.shape[0], 4))'''

"# Checking the percentage of data that would be kept after removing outliers\nprint('Percentage of data kept after removing outliers:')\nprint(np.round(X_train_mpg.shape[0] / X_train.shape[0], 4))\nprint(np.round(X_val_mpg.shape[0] / X_val.shape[0], 4))"

- Since the outliers constitute more than 3% of the data, they will not be removed

**EngineSize**

In [87]:
X_train[X_train['engineSize'] > 5]

Brand      model  year transmission  mileage fuelType    tax   mpg  \
carID                                                                          
41531  Mercedes   SL CLASS  2016    Automatic   6200.0   Petrol  350.0  28.0   
2487       Audi         R8  2019    Semi-Auto   7800.0   Petrol  145.0  21.4   
45626  Mercedes   SL CLASS  2016    Semi-Auto  21681.0   Petrol  350.0  28.0   
37895  Mercedes  GLE Class  2019    Semi-Auto  11545.0   Petrol  145.0  23.9   
35290  Mercedes    C Class  2014    Automatic  56444.0   Petrol  350.0  23.5   
39752  Mercedes    C Class  2014    Automatic  56444.0   Petrol    NaN   NaN   
2022       Audi         R8  2019    Automatic   8175.0   Petrol  145.0  21.6   
40976  Mercedes  GLE Class  2019    Semi-Auto      9.0   Petrol  145.0  23.7   
46064  Mercedes  GLE Class  2017    Semi-Auto   6000.0   Petrol  145.0  23.9   
43741  Mercedes   SL CLASS  2019    Automatic    105.0   Petrol  145.0  28.0   
1697        NaN         R8  2014    Automatic  35000.0   Petrol  350.0  21.9   
2736       Audi         R8  2019    Semi-Auto    500.0   Petrol  145.0  21.4   
44412  Mercedes   SL CLASS  2019    Automatic     10.0   Petrol  145.0  28.0   
2743       Audi         R8  2018    Semi-Auto   3800.0   Petrol  145.0  23.0   
45353  Mercedes   CL Class  2002    Automatic  77000.0   Petrol  325.0  21.1   
5953       Audi         R8  2019    Semi-Auto     10.0   Petrol  150.0  21.4   
35117  Mercedes    C Class  2013    Automatic  39000.0   Petrol  350.0  23.5   
37660  Mercedes   SL CLASS  2019    Semi-Auto   1776.0   Petrol  145.0  28.0   
38953  Mercedes  GLE Class  2018    Automatic   5234.0   Petrol  145.0  23.9   
39737  Mercedes    M Class  2014    Semi-Auto  33271.0   Petrol  350.0  23.9   
3167       Audi         A6  2006    Automatic  98000.0   Petrol  350.0  21.1   
44937  Mercedes    C Class  2013    Automatic  41866.0   Petrol  350.0  23.5   
42286  Mercedes    C Class  2014    Semi-Auto  24175.0   Petrol    NaN   NaN   
38980  Mercedes    C Class  2013    Semi-Auto  43442.0   Petrol    NaN   NaN   
35970  Mercedes    G Class  2015    Semi-Auto  10000.0   Petrol  350.0  20.5   
44315  Mercedes  GLE Class  2019    Automatic   3574.0   Petrol  145.0  23.7   
5324       Audi         R8  2019    Automatic   3000.0   Petrol  145.0  21.4   
35674  Mercedes   SL CLASS  2019    Automatic    221.0   Petrol  145.0  28.0   
44794  Mercedes    C Class  2014    Semi-Auto  37000.0   Petrol  350.0  23.5   
46536  Mercedes    C Class  2013    Automatic  44000.0   Petrol    NaN   NaN   
46012  Mercedes   SL CLASS  2011    Automatic   3000.0   Petrol  350.0  21.4   
39725  Mercedes  GLE Class  2017    Semi-Auto  23000.0   Petrol  145.0  23.9   
35305  Mercedes    S Class  2016          NaN  19953.0   Petrol  350.0  28.0   
4111       Audi         R8  2014    Automatic  31930.0   Petrol  350.0  21.9   
1950       Audi         R8  2019    Automatic   1000.0   Petrol  145.0  32.8   
46040  Mercedes  GLS Class  2017    Automatic  45239.0   Petrol  150.0  23.0   
43725  Mercedes    C Class  2014    Semi-Auto  24175.0   Petrol  350.0  23.5   
40664  Mercedes    E Class  2015    Automatic  83079.0   Petrol  350.0  28.8   
9197        BMW   7 Series  2017    Automatic  11297.0   Petrol  145.0  22.1   
2020       Audi         R8  2016    Automatic  28888.0   Petrol  350.0  24.1   
2424       Audi         R8  2019    Automatic    100.0   Petrol  145.0  24.1   
35098  Mercedes    C Class  2005    Automatic  73000.0   Petrol    NaN   NaN   
40094  Mercedes    C Class  2013    Automatic  39000.0   Petrol    NaN   NaN   
36394  Mercedes   SL CLASS  2019    Automatic     50.0   Petrol  145.0  28.0   

       engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                        
41531         5.5           79.0               4       <NA>  
2487          5.2           72.0               4          0  
45626         5.5           71.0               1          0  
37895         5.5  

In [88]:
# Cap engineSize: replacing all numbers above 5 by 5
X_train["engineSize"] = X_train["engineSize"].clip(lower=0.5, upper=5)
X_val["engineSize"] = X_val["engineSize"].clip(lower=0.5, upper=5)

In [89]:
'''# Creating a df of observations where engineSize < 5
X_train_eng= X_train[X_train['engineSize'] < 5]
X_val_eng= X_val[X_val['engineSize'] < 5]'''

"# Creating a df of observations where engineSize < 5\nX_train_eng= X_train[X_train['engineSize'] < 5]\nX_val_eng= X_val[X_val['engineSize'] < 5]"

In [90]:
'''# Checking the percentage of data that would be kept after removing outliers
print('Percentage of data kept after removing outliers:')
print(np.round(X_train_eng.shape[0] / X_train.shape[0], 4))
print(np.round(X_val_eng.shape[0] / X_val.shape[0], 4))'''

"# Checking the percentage of data that would be kept after removing outliers\nprint('Percentage of data kept after removing outliers:')\nprint(np.round(X_train_eng.shape[0] / X_train.shape[0], 4))\nprint(np.round(X_val_eng.shape[0] / X_val.shape[0], 4))"

In [91]:
'''# Removing from the datasets
X_train= X_train[X_train['engineSize'] < 5]
X_val= X_val[X_val['engineSize'] < 5]'''

"# Removing from the datasets\nX_train= X_train[X_train['engineSize'] < 5]\nX_val= X_val[X_val['engineSize'] < 5]"

### 4.7. Treating Missing Values

#### 4.7.1. Numerical Variables 

**KNN Imputer**

In [92]:
X_train[metric_features].isna().sum().sort_values(ascending=False)

tax               5609
mpg               5385
engineSize        1414
paintQuality%     1316
mileage           1243
hasDamage         1072
previousOwners    1069
year                 0
dtype: int64

In [93]:
X_val[metric_features].isna().sum().sort_values(ascending=False)

tax               2458
mpg               2373
engineSize         574
mileage            550
paintQuality%      527
hasDamage          445
previousOwners     443
year                 0
dtype: int64

- Most of our variables are MAR (missing at random), which means that missingness depends on known variables. For example, we can imply that milage depends on brand, year and engine size; mpg depends on fuel type and model; tax depends on fuel type and year, etc.
- This means that the "correct" value for a missing record would not reply on the global mean, but depends on similiar cars. Therefore, the KNN imputer method is a good solution for this type of problem since it is capable of dealing with MAR, while capturing non linear relationships. 

In [94]:
#scalling X_train and X_val since KNN imputer uses distances

#numerical variables whose missing values need to be filled
numeric_cols = ['tax', 'mpg', 'mileage', 'paintQuality%', 'engineSize', 'hasDamage', 'previousOwners']
scaler = MinMaxScaler()

# fitting the scaler only on training dataset (to avoid leakage)
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])

# transforming validation dataset using the same scaling
X_val[numeric_cols] = scaler.transform(X_val[numeric_cols])

In [95]:
knn = KNNImputer(n_neighbors=5, weights='distance')

X_train[numeric_cols] = knn.fit_transform(X_train[numeric_cols])
X_val[numeric_cols] = knn.transform(X_val[numeric_cols])

In [96]:
X_train[metric_features].isna().sum().sort_values(ascending=False)

year              0
mileage           0
tax               0
mpg               0
engineSize        0
paintQuality%     0
previousOwners    0
hasDamage         0
dtype: int64

In [97]:
X_val[metric_features].isna().sum().sort_values(ascending=False)

year              0
mileage           0
tax               0
mpg               0
engineSize        0
paintQuality%     0
previousOwners    0
hasDamage         0
dtype: int64

#### 4.7.2. Categorical Variables

**Filling with the mode**

In [98]:
X_train[non_metric_features].isna().sum().sort_values(ascending=False)

transmission    1604
model           1153
fuelType        1110
Brand           1019
dtype: int64

In [99]:
X_val[non_metric_features].isna().sum().sort_values(ascending=False)

transmission    614
fuelType        520
model           507
Brand           460
dtype: int64

In [100]:
cat_imputer = SimpleImputer(strategy='most_frequent')

X_train.loc[:, non_metric_features] = cat_imputer.fit_transform(X_train[non_metric_features])
X_val.loc[:, non_metric_features] = cat_imputer.transform(X_val[non_metric_features])

In [101]:
X_train[non_metric_features].isna().sum().sort_values(ascending=False)

Brand           0
model           0
transmission    0
fuelType        0
dtype: int64

In [102]:
X_val[non_metric_features].isna().sum().sort_values(ascending=False)

Brand           0
model           0
transmission    0
fuelType        0
dtype: int64

### 4.8. Feature Engineering

#### 4.8.1. Creating New Variables

In [103]:
X_train['engineEfficiency'] = X_train['mpg'] / X_train['engineSize']
X_val['engineEfficiency'] = X_val['mpg'] / X_val['engineSize']

#### 4.8.2. Encoding Categorical Features

- Frequency encoding is used to transform the variables Brand and model into numerical, as these have a high cardinality, while transmission and fuelType was transformed into dummy variables.

In [104]:
freq_encoding_brand = X_train['Brand'].value_counts()
X_train['brand_encoded'] = X_train['Brand'].map(freq_encoding_brand)
X_val['brand_encoded'] = X_val['Brand'].map(freq_encoding_brand)

In [105]:
freq_encoding_model = X_train['model'].value_counts()
X_train['model_encoded'] = X_train['model'].map(freq_encoding_model)
X_val['model_encoded'] = X_val['model'].map(freq_encoding_model)

In [106]:
X_train = pd.get_dummies(X_train, columns=['transmission'], prefix='Transmission', drop_first=True)
X_val = pd.get_dummies(X_val, columns=['transmission'], prefix='Transmission', drop_first=True)

- We observed that the fuelType variable contained, only 4 Electric cars, which is an extremely low representation for a category, and 46 rows defined as "other". To prevent overfitting and unstable coefficients, these categories were grouped together into the Other class.

In [107]:
print(X_train["fuelType"].value_counts())
print(X_val["fuelType"].value_counts())

fuelType
Petrol      29263
Diesel      21085
Hybrid       1519
Electric        3
Name: count, dtype: int64
fuelType
Petrol    12536
Diesel     9035
Hybrid      670
Name: count, dtype: int64


In [108]:
rare_fuels = ['Electric', 'Other']
X_train['fuelType'] = X_train['fuelType'].replace(rare_fuels, 'Other')
X_val['fuelType'] = X_val['fuelType'].replace(rare_fuels, 'Other')

X_train = pd.get_dummies(X_train, columns=['fuelType'], prefix='Fuel', drop_first=True)
X_val = pd.get_dummies(X_val, columns=['fuelType'], prefix='Fuel', drop_first=True)

In [109]:
X_train, X_val = X_train.align(X_val, join='left', axis=1, fill_value=0)
#ensures that X_train and X_val have the same colums to avoid mismatch

bool_cols = X_train.select_dtypes(include=['bool', 'int8']).columns
#bool_cols = X_train.select_dtypes(include=['bool']).columns
X_train[bool_cols] = X_train[bool_cols].astype(int)
X_val[bool_cols] = X_val[bool_cols].astype(int)

In [110]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51870 entries, 42520 to 15659
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Brand                   51870 non-null  object 
 1   model                   51870 non-null  object 
 2   year                    51870 non-null  Int32  
 3   mileage                 51870 non-null  float64
 4   tax                     51870 non-null  float64
 5   mpg                     51870 non-null  float64
 6   engineSize              51870 non-null  float64
 7   paintQuality%           51870 non-null  float64
 8   previousOwners          51870 non-null  float64
 9   hasDamage               51870 non-null  float64
 10  engineEfficiency        51870 non-null  float64
 11  brand_encoded           51870 non-null  int64  
 12  model_encoded           51870 non-null  int64  
 13  Transmission_Manual     51870 non-null  int64  
 14  Transmission_Semi-Auto  51870 non-null 

In [111]:
X_val.isna().sum().sort_values(ascending=False)

model_encoded             4
Brand                     0
model                     0
year                      0
tax                       0
mileage                   0
engineSize                0
paintQuality%             0
previousOwners            0
mpg                       0
hasDamage                 0
engineEfficiency          0
brand_encoded             0
Transmission_Manual       0
Transmission_Semi-Auto    0
Fuel_Hybrid               0
Fuel_Other                0
Fuel_Petrol               0
dtype: int64

In [112]:
mean_freq = freq_encoding_model.mean()
X_val['model_encoded'] = X_val['model'].map(freq_encoding_model).fillna(mean_freq)

In [113]:
X_val.isna().sum().sort_values(ascending=False)

Brand                     0
model                     0
year                      0
mileage                   0
tax                       0
mpg                       0
engineSize                0
paintQuality%             0
previousOwners            0
hasDamage                 0
engineEfficiency          0
brand_encoded             0
model_encoded             0
Transmission_Manual       0
Transmission_Semi-Auto    0
Fuel_Hybrid               0
Fuel_Other                0
Fuel_Petrol               0
dtype: int64

In [114]:
X_train = X_train.drop(['Brand', 'model'], axis=1)
X_val = X_val.drop(['Brand', 'model'], axis=1)

In [115]:
# ensuring that y_train has the same rows X_train
y_train = y_train.loc[X_train.index]
y_val = y_val.loc[X_val.index]

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

X_train shape: (51870, 16)
y_train shape: (51870,)


### 4.9. Scaling

In [116]:
#checking if the variable created has some infinite values
print(np.isinf(X_train["engineEfficiency"]).sum())
print(np.isinf(X_val["engineEfficiency"]).sum())

1
3


In [117]:
#replace infinite by missing values
X_train = X_train.replace({"engineEfficiency": {np.inf: np.nan, -np.inf: np.nan}})
X_val = X_val.replace({"engineEfficiency": {np.inf: np.nan, -np.inf: np.nan}})

In [118]:
#fill the missing values using the mode 
X_train['engineEfficiency'] = cat_imputer.fit_transform(X_train[['engineEfficiency']])
X_val['engineEfficiency'] = cat_imputer.transform(X_val[['engineEfficiency']])

- We replaced the infinites by missing values and fill them because, if there were infinites in *engineEfficiency*, the scaled would not work. 

In [119]:
#variables that are not scalled yet
rest_var = ['year', 'brand_encoded', 'model_encoded', 'engineEfficiency' ]

# fitting the scaler only on training dataset (to avoid leakage)
X_train[rest_var] = scaler.fit_transform(X_train[rest_var])

# transforming validation dataset using the same scaling
X_val[rest_var] = scaler.transform(X_val[rest_var])

In [120]:
#checking if X_train and y_train have the same number of rows
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

X_train shape: (51870, 16)
y_train shape: (51870,)


In [121]:
#checking if X_val and y_val have the same number of rows
print("X_val shape:", X_train.shape)
print("y_val shape:", y_train.shape)

X_val shape: (51870, 16)
y_val shape: (51870,)


In [122]:
'''scaler = MinMaxScaler()

scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train) 
X_val_scaled = scaler.transform(X_val)

X_train_scaled = pd.DataFrame(X_train_scaled, columns = X_train.columns).set_index(X_train.index)
X_val_scaled = pd.DataFrame(X_val_scaled, columns = X_val.columns).set_index(X_val.index)

X_train = X_train_scaled
X_val = X_val_scaled

# ensuring that y_train has the same rows X_train
y_train = y_train.loc[X_train.index]
y_val = y_val.loc[X_val.index]

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)'''

'scaler = MinMaxScaler()\n\nscaler.fit(X_train)\n\nX_train_scaled = scaler.transform(X_train) \nX_val_scaled = scaler.transform(X_val)\n\nX_train_scaled = pd.DataFrame(X_train_scaled, columns = X_train.columns).set_index(X_train.index)\nX_val_scaled = pd.DataFrame(X_val_scaled, columns = X_val.columns).set_index(X_val.index)\n\nX_train = X_train_scaled\nX_val = X_val_scaled\n\n# ensuring that y_train has the same rows X_train\ny_train = y_train.loc[X_train.index]\ny_val = y_val.loc[X_val.index]\n\nprint("X_train shape:", X_train.shape)\nprint("y_train shape:", y_train.shape)'

### Pre Processing Test Data

#### Dataset Overview

In [123]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32567 entries, 0 to 32566
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   carID           32567 non-null  int64  
 1   Brand           31918 non-null  object 
 2   model           31917 non-null  object 
 3   year            31914 non-null  float64
 4   transmission    31944 non-null  object 
 5   mileage         31878 non-null  float64
 6   fuelType        31911 non-null  object 
 7   tax             29259 non-null  float64
 8   mpg             29279 non-null  float64
 9   engineSize      31939 non-null  float64
 10  paintQuality%   31942 non-null  float64
 11  previousOwners  31970 non-null  float64
 12  hasDamage       31970 non-null  float64
dtypes: float64(8), int64(1), object(4)
memory usage: 3.2+ MB


In [124]:
test_data.head(20)

carID     Brand          model         year transmission       mileage  \
0    89856   Hyundai            I30  2022.878006    Automatic  30700.000000   
1   106581        VW         Tiguan  2017.000000    Semi-Auto -48190.655673   
2    80886       BMW       2 Series  2016.000000    Automatic  36792.000000   
3   100174      Opel    Grandland X  2019.000000       Manual   5533.000000   
4    81376       BMW       1 Series  2019.000000    Semi-Auto   9058.000000   
5    85391      Ford         Fiesta  2018.000000       Manual  29626.000000   
6    82175       BMW             X1  2016.000000       Manual  57717.000000   
7    95250  Mercedes        B Class  2017.000000       Manual  14005.000000   
8    85071      Ford          Focus  2011.000000       Manual  68274.000000   
9    96210     Skoda         Superb  2019.000000       Manual  20632.000000   
10   80317       BMW       5 Series  2019.000000    Semi-Auto   9131.000000   
11   92731  Mercedes        C Class  2018.000000       unknow  20173.000000   
12  107704        VW             Up  2018.000000    Automatic   2154.000000   
13   98302     Toyot           Aygo  2017.000000       Manual  13255.000000   
14  107055        VW           Golf  2017.000000    Semi-Auto  20168.000000   
15   94621  Mercedes        C Class  2019.000000    Automatic    750.000000   
16   91709  Mercedes         M CLAS  2015.000000    Automatic  68279.000000   
17   98193    Toyota   Land Cruiser  2019.000000    Automatic   6836.000000   
18   76189      Audi             TT  2017.000000       Manual  30562.000000   
19   86871      Ford          Focus          NaN       Manual  10585.000000   

   fuelType    tax       mpg  engineSize  paintQuality%  previousOwners  \
0    petrol  205.0  41.50000         1.6           61.0             3.0   
1    Petrol  150.0  38.20000         2.0           60.0             2.0   
2    Petrol  125.0  51.40000         1.5           94.0             2.0   
3    Petrol  145.0  44.10000         1.2           77.0             1.0   
4    Diesel  150.0  51.40000         2.0           45.0             4.0   
5    Petrol  145.0  65.70000         1.0           64.0             1.0   
6     Diese  125.0  58.90000         2.0           50.0             1.0   
7    Diesel  145.0  65.70000         NaN           64.0             4.0   
8    Petrol  145.0  47.90000         1.6           71.0             4.0   
9    Diesel  145.0  64.20000         2.0           99.0             3.0   
10   Diesel  145.0  62.80000         2.0           73.0             3.0   
11   Diesel  145.0  61.40000         2.1           78.0             0.0   
12   Petrol  145.0  94.78638         1.0           40.0             0.0   
13   Petrol  145.0  69.00000         1.0           35.0             3.0   
14   Petrol  200.0  39.80000         2.0           76.0             1.0   
15   Petrol  150.0  30.40000         3.0           76.0             1.0   
16   Diesel  300.0  39.20000         NaN           53.0             3.0   
17   Diesel  145.0  30.10000         2.8           90.0             0.0   
18   Diesel  145.0  62.80000         2.0            NaN             1.0   
19   Petrol  145.0  57.70000         1.0           73.0             0.0   

    hasDamage  
0         0.0  
1         0.0  
2         0.0  
3         0.0  
4         0.0  
5         0.0  
6         0.0  
7         0.0  
8         0.0  
9         0.0  
10        0.0  
11        NaN  
12        0.0  
13        0.0  
14        0.0  
15        0.0  
16        0.0  
17        0.0  
18        0.0  
19        0.0

#### Changing Datatypes

In [125]:
#set index to 'carID'
test_data.set_index('carID', inplace = True)

In [126]:
# Rounds the floats and changes them to integers

#year to integer
test_data['year'] = test_data['year'].round().astype('Int32')
test_data['year'] = test_data['year'].round().astype('Int32')

#previousOwners to integer
test_data['previousOwners'] = test_data['previousOwners'].round().astype('Int32')
test_data['previousOwners'] = test_data['previousOwners'].round().astype('Int32')

#hasDamaged to boolean
test_data['hasDamage'] = test_data['hasDamage'].astype('Int8')
test_data['hasDamage'] = test_data['hasDamage'].astype('Int8')

#### Handling Incoherencies

In [127]:
#correcting spelling mistakes of 'brand' for test_data

correct_brand = {
    'VW': ['V', 'vw', 'v', 'W', 'w'],
    'Toyota': ['Toyot', 'TOYOTA', 'oyota', 'toyota', 'OYOTA', 'TOYOT', 'toyot', 'oyot'],
    'Audi': ['udi', 'AUDI', 'audi', 'Aud', 'aud', 'UDI', 'AUD'],
    'Ford': ['FOR', 'ord', 'For', 'FORD', 'ford', 'for', 'or', 'ORD'],
    'BMW': ['MW', 'bmw', 'BM', 'mw', 'M', 'bm'],
    'Skoda': ['koda', 'skoda', 'SKODA', 'Skod', 'kod', 'SKOD', 'KODA', 'skod'],
    'Opel': ['Ope', 'opel', 'pel', 'pe', 'OPEL', 'PEL', 'OPE', 'ope'],
    'Mercedes': ['mercedes', 'Mercede', 'MERCEDES', 'ercedes', 'mercede', 'ERCEDES', 'ercede', 'MERCEDE'],
    'Hyundai': ['yundai', 'Hyunda', 'hyundai', 'HYUNDAI', 'yunda', 'HYUNDA', 'ud', 'hyunda', 'YUNDAI']
}

# Create a reverse lookup dictionary (each incorrect form maps to the correct one)
replacement_dict = {variant: correct for correct, variants in correct_brand.items() for variant in variants}

# Replace incorrect brand names with the correct ones
test_data["Brand"] = test_data["Brand"].replace(replacement_dict)

# Verify the cleaning
print(test_data["Brand"].unique())

['Hyundai' 'VW' 'BMW' 'Opel' 'Ford' 'Mercedes' 'Skoda' 'Toyota' 'Audi' nan]


In [128]:
##correcting spelling mistakes of 'model' for test_data

correct_model = {
    'Golf': [' GOLF', ' Gol', ' golf', 'golf', ' Golf', ' gol', ' GOL', 'Gol', 'GOLF'],
    'Yaris': [' Yaris', ' YARIS', ' Yari', ' yaris', ' yari', 'Yari', ' YARI', 'yaris', 'YARIS'],
    'Q2': [' q2', ' Q2'],
    '2 Series': [' 2 series', ' 2 serie', '2 Series', ' 2 SERIES', ' 2 Serie', '2 Serie', ' 2 Series'],
    '3 Series': [' 3 Series', ' 3 Serie', ' 3 series', ' 3 SERIES', ' 3 serie', '3 Serie'],
    'A3': [' A3', ' a3'],
    'Octavia': [' Octavi', ' OCTAVIA', ' Octavia', ' octavia', 'Octavi', 'octavia', ' octavi', ' OCTAVI'],
    'Passat': [' PASSAT', ' passat', ' Passa', 'Passat', ' Passat', 'PASSAT', ' PASSA'],
    'Insignia': [' Insigni', ' INSIGNIA', ' insignia', ' Insignia', ' INSIGNI', 'Insigni'],
    'Fabia': [' Fabia', ' fabia', ' FABIA', ' Fabi', 'FABIA'],
    'A Class': [' A Clas', ' A Class', ' a class', ' A CLASS', 'a class', 'A CLASS', ' a clas'],
    'Ka+': [' Ka+', ' KA+', ' ka+', 'ka+'],
    'GLC Class': [' GLC Class', ' GLC CLASS', ' GLC Clas', ' glc class', ' glc clas'], 
    'I30': [' i30', ' I30'],
    'C Class': [' C Clas', ' C CLASS', ' c class', 'C Clas', ' C CLAS', 'c class', ' c clas', ' C Class', 'C CLASS'],
    'Polo': [' POLO', ' Polo', ' polo', ' Pol', ' POL', 'Pol', 'POLO'],
    'E Class': [' E Class', ' E Clas', ' E CLASS', ' e class', 'E CLASS', 'e class'],
    'Q5': [' Q5', ' q5', 'q5'],
    'Up': ['U', ' up', ' UP', ' Up', ' U', 'UP'],
    'Fiesta': [' FIESTA', ' fiesta', ' Fiest', ' Fiesta', 'fiesta', 'Fiest', ' FIESTA', 'FIESTA', ' fiest'],
    'C-HR': [' C-H', ' c-hr', ' C-HR', ' c-h'],
    'Mokka X': [' mokka x', ' MOKKA X', ' Mokka X'],
    'Corsa': [' Corsa', ' corsa', ' Cors', ' CORSA', ' cors', ' CORS', 'corsa'],
    'Astra': [' ASTRA', ' Astr', ' Astra', ' astra', 'ASTRA', 'astra'],
    'TT': [' tt', ' TT', ' T'],
    '5 Series': [' 5 Series', ' 5 Serie', ' 5 SERIES', ' 5 series', '5 SERIES', ' 5 SERIE'],
    'Aygo': [' aygo', ' ayg', ' AYGO', ' Ayg', ' Aygo', 'aygo', ' AYG'],
    '4 Series': [' 4 SERIES', ' 4 Serie', ' 4 serie', '4 series', '4 Series', ' 4 Series', ' 4 series'],
    'SLK': [' slk', ' SLK'],
    'Viva': [' viva', ' Viva', ' VIVA', ' Viv', 'viva'],
    'Focus': [' Focus', ' Focu', ' FOCUS', ' focus', ' FOCU', 'focus', 'Focu', ' focu', 'FOCUS'],
    'EcoSport': [' EcoSpor', ' ECOSPORT', ' ecosport', ' EcoSport'],
    'X-CLASS': [' x-clas', ' X-CLAS', ' x-class', ' X-CLASS'],
    'CL Class': [' cl class', ' CL Clas', ' CL CLASS', ' CL Class'],
    'IX20': [' ix20', ' IX20'],
    'Rapid': [' Rapi', ' rapid', ' Rapid'],
    'Auris': [' Auris', ' AURIS', ' auris', ' Auri'],
    'I20': [' i20', ' I20'],
    'X3': [' x3', ' X3'],
    'A8': [' A8', 'a8'],
    'GLS Class': [' GLS Clas', ' GLS CLASS', ' gls class', ' GLS Class'],
    'B-MAX': [' B-MA', ' B-MAX', 'B-MA', ' b-max'],
    'A4': [' A4', ' a4'],
    'Kona': [' KONA', ' Kon', ' Kona', ' KON', ' kona'],
    'I10': [' i10', ' I10'],
    'A1': [' A1', ' a1'],
    'Mokka': [' Mokka ', ' Mokk', ' Mokka', ' mokka ', ' mokka', ' MOKKA', 'Mokka ', 'Mokk'],
    'S-MAX': [' S-MA', ' s-max', ' S-MAX', ' s-ma'],
    'X2': [' x2', ' X2'],
    'Crossland X': [' crossland x', ' CROSSLAND X', ' Crossland X'],
    'Tiguan': [' Tiguan', ' tiguan', ' Tigua', ' TIGUAN', ' TIGUA', 'Tigua', 'TIGUAN', 'tiguan', ' tigua'],
    'A5': [' A5', ' a5', 'a5'],
    'GLE Class': [' GLE Clas', ' GLE Class', ' gle class', ' GLE CLASS'],
    'Zafira': [' Zafira', ' Zafir', ' ZAFIRA', ' zafira', 'Zafir', ' ZAFIR'],
    'Ioniq': [' Ioni', ' Ioniq', ' IONIQ', 'IONIQ', ' ioniq'],
    'A6': [' A6', ' a6'],
    'Yeti Outdoor': [' yeti outdoor', ' Yeti Outdoor', ' YETI OUTDOOR', ' Yeti Outdoo', ' yeti outdoor', 'yeti outdoor', ' yeti outdoo'],
    'X1': [' x1', 'x1', ' X1'],
    'Scala': [' SCALA', ' Scala', ' scala', ' Scal', ' scal'],
    'S Class': [' S Class', ' S Clas', ' s class', ' S CLASS'],
    '1 Series': [' 1 Series', ' 1 SERIES', ' 1 Serie', ' 1 series', '1 SERIES', ' 1 SERIE', '1 series', ' 1 serie'],
    'Kamiq': [' KAMIQ', ' KAMI', ' kamiq', ' Kamiq'],
    'Kuga': [' Kug', ' KUGA', ' kuga', 'Kuga', ' Kuga', 'kuga'],
    'Tourneo Connect': [' tourneo connect', ' Tourneo Connect'],
    'Q7': [' q7', ' Q7'],
    'GLA Class': [' GLA Class', ' GLA CLASS', ' GLA Clas', ' gla class'],
    'Arteon': [' arteon', ' Arteon', ' Arteon'],
    'SL CLASS': [' SL CLAS', ' SL CLASS', ' sl class', ' SL'],
    'Tucson': [' Tucson', ' TUCSON', ' Tucso', ' tucson', ' TUCSO', 'Tucso'],
    'Santa Fe': [' Santa F', ' santa fe', ' SANTA FE', ' Santa Fe'],
    'Grandland X': [' Grandland X', ' grandland x', ' GRANDLAND X'],
    'RAV4': [' rav4', 'RAV4', 'RAV', ' RAV', 'rav4', ' rav', ' RAV4'],
    'Touran': [' Touran', 'Toura', ' TOURAN', ' touran', ' Toura', ' TOURA'],
    'Citigo': [' Citig', ' citigo', ' Citigo', ' CITIGO', 'CITIGO'],
    'Roomster': [' Roomste', ' Roomster'],
    'Prius': [' PRIUS', ' Prius', 'Prius', ' prius'],
    'Corolla': [' corolla', ' COROLLA', ' Coroll', ' Corolla', 'corolla'],
    'B Class': [' b class', ' B Clas', ' B Class', ' B CLASS', 'b class'],
    'Sharan': [' sharan', ' Shara', ' Sharan', ' SHARAN'],
    'Kodiaq': [' Kodia', ' kodiaq', 'kodiaq', ' KODIAQ', ' Kodiaq'],
    'V Class': [' V Clas', ' V CLASS', ' V Class', ' v class'],
    'Caddy Maxi Life': [' Caddy Maxi Lif', ' Caddy Maxi Life'],
    'Superb': [' Superb', ' Super', ' SUPERB', ' superb', ' super'],
    'T-Roc': [' T-Roc', ' T-RO', ' t-roc', ' T-Ro', ' T-ROC'],
    'Combo Life': [' COMBO LIFE', ' combo life', ' Combo Lif', 'COMBO LIFE', ' Combo Life'],
    'Beetle': [' Beetl', ' Beetle', ' beetle'],
    'Galaxy': [' GALAXY', ' Galax', ' galaxy', ' Galaxy'],
    'M3': [' M3', ' m3'],
    'Gtc': [' gtc', ' GTC', ' gtc', 'gtc', 'GTC'],
    'X4': [' X4', ' x4'],
    'KA': [' Ka', ' ka', ' K', ' KA'],
    'IX35': [' ix35', ' IX35'],
    'Grand Tourneo Connect': [' Grand Tourneo Connec', ' Grand Tourneo Connect'],
    'M4': [' m4', ' M4'],
    'Tourneo Custom': [' tourneo custom', ' Tourneo Custo', ' Tourneo Custom'],
    'Z4': [' Z4', ' z4'],
    'X5': [' X5', ' x5'],
    'Meriva': [' Meriva', ' MERIVA', ' Meriv', ' meriva'],
    'RS6': [' RS6'],
    'Verso': [' VERSO', ' verso', ' Verso', ' Vers'],
    'Touareg': [' Touareg', ' TOUAREG', ' touareg', ' Touare'],
    'Mondeo': [' MONDEO', ' Mondeo', ' mondeo', ' MONDE', ' Monde'],
    'Shuttle': [' shuttle', ' Shuttle', ' SHUTTLE'],
    'CLS Class': [' CLS Class', ' cls class', ' CLS Clas', ' CLS CLASS'], 
    'C-MAX': [' C-MAX', ' c-max', ' C-MA'],
    'Puma': [' puma', ' PUMA', ' Puma', 'Pum', ' Pum'],
    'CLA Class': [' CLA Class', ' CLA CLASS', ' cla class', ' CLA Clas'],
    'I40': [' I40', ' i40'],
    'Q3': [' q3', ' Q3'],
    'Tiguan Allspace': [' TIGUAN ALLSPACE', ' tiguan allspace', ' Tiguan Allspac', ' Tiguan Allspace'],
    '6 Series': [' 6 SERIES', ' 6 series', ' 6 Series', ' 6 Serie'],
    'Caravelle': [' caravelle', ' Caravell', ' Caravelle'],
    'Karoq': [' Karoq', ' karoq', ' KAROQ', ' Karo'],
    'I3': [' i3', 'i3', ' I3'],
    'Grand C-MAX': [' GRAND C-MAX', ' grand c-max', ' Grand C-MA', ' Grand C-MAX'],
    'T-Cross': [' T-Cros', ' T-CROSS', ' T-Cross', ' t-cros', ' t-cross'],
    'A7': [' a7', ' A7'],
    'Golf SV': [' Golf SV', ' golf sv', ' GOLF SV'],
    'A': [' a', ' A'],
    'GT86': [' gt86', ' GT86'],
    'Yeti': [' yeti', ' Yet', ' Yeti', ' YETI'],
    'X': [' x', ' X'],
    'Land Cruiser': [' Land Cruise', ' Land Cruiser', ' land cruiser'],
    'EDGE': [' Edge', ' edge', ' Edg', ' EDGE'],
    'X6': [' X6'],
    'Fusion': [' Fusion', ' fusion'],
    'GL Class': [' GL CLASS', ' gl class', ' GL Class', ' GL Clas'],
    'Scirocco': [' scirocco', ' SCIROCCO', ' Scirocc', ' Scirocco'],
    'Z3': [' Z3'],
    'Hilux': [' hilux', ' Hilux', ' Hilu', ' HILU'],
    'Amarok': [' amarok', ' Amarok', ' Amaro'],
    'CC': [' cc', ' CC'],
    '7 Series': [' 7 Serie', ' 7 SERIES', ' 7 series', ' 7 Series'],
    'Avensis': [' AVENSIS', ' avensis', ' Avensis'],
    'M Class': [' m class', ' M CLASS', ' M Class', ' M Clas', ' M CLAS'],
    'Grandland': [' grandland ', ' Grandland '],
    'Zafira Tourer': [' Zafira Toure', ' ZAFIRA TOURER', ' Zafira Tourer', ' zafira tourer'],
    'R8': [' R8', ' r8'],
    'Mustang': [' mustang', ' Mustang'],
    'Q8': [' Q8'],
    'CLK': [' CLK'],
    'RS3': [' RS3'],
    'Jetta': [' JETTA', ' Jetta', ' jetta', 'Jetta' ],
    'Supra': [' Supra'],
    'X7': [' X7'],
    'SQ7': [' SQ7', ' sq7'],
    'S3': [' s3', ' S3'],
    'Arteon': [' Arteo', 'Arteo', ' ARTEON', ' arteon', ' Arteon'],
    'GLB Class': [' glb class', ' GLB Class'],
    'Adam': [' Ada', ' adam', ' ADAM', ' Adam'],
    'M5': [' M5',' m5'],
    'Golf S': [' golf s', ' Golf S'],
    'Vectra': ['Vectra', ' Vectra', ' VECTRA', 'VECTRA'],
    '8 Series': [' 8 SERIES', ' 8 Serie', ' 8 Series', ' 8 series'],
    'Urban Cruiser': [' Urban Cruise', ' Urban Cruiser'],
    'Fox': ['fox', ' fox', ' Fox'], 
    'Q': [' Q'], 
    'M2': [' M2'], 
    'RS4':[' RS4'], 
    'Veloster': [' Veloster', ' Veloste'],  
    'IQ': [' IQ'], 
    'Agila': [' AGILA', ' Agila'], 
    'I2': [' I2'], 
    'Antara': [' Antara', ' antara'], 
    'G Class': [' G Class', ' G CLAS'], 
    'Caddy Life': [' Caddy Life', ' Caddy'],
    'R Class': [' R Class'], 
    'I800': [' I800'],
    'Amica': [' Amica'], 
    'Crossland': [' Crossland '],
    'Proace Verso': [' proace verso', ' PROACE VERSO', 'PROACE VERSO'],
    'Camry': [' Camry', 'Camry', ' Camr'], 
    'Tigra': [' Tigra'], 
    'Eos': [' Eos'], 
    'M': [' M'],
    'California': [' Californi', ' California'], 
    'Ampera': [' Ampera'], 
    'I1': [' I1'], 
    'S5': [' S5'], 
    'CLC Class': [' CLC Class'], 
    'Shara': [' SHARA'], 
    'I8': [' i8', 'i8'], 
    'RS7': [' RS7'], 
    'Transit Tourneo': [' Transit Tourneo'], 
    'I4': [' I4'], 
    'S4':[' S4'], 
    'Terracan': [' Terracan'], 
    'Cascada': [' Cascada'], 
    'S8': [' S8'], 
    'A2':[' A2'], 
    'Vivaro':[' Vivaro'],
    'RS5':[' RS5'],
    'SQ5':[' SQ5'], 
    'Getz':[' Getz'], 
    'M6':[' M6'], 
    'Caddy Maxi': [' Caddy Maxi'], 
    'Z':[' Z'], 
    'Verso-S': [' Verso-S'], 
    'Kadjar': [' Kadjar'], 
    'I80': [' I80'], 
    'Streetka': [' Streetka'],
    'RS': [' RS'], 
    'I': [' i'], 
    'Ranger': [' Ranger'], 
    'IX2': [' IX2'], 
    'Escort': [' Escort'],
    'Accent': [' Accent']
}

# Create a reverse lookup dictionary (each incorrect form maps to the correct one)
replacement_dict = {variant: correct for correct, variants in correct_model.items() for variant in variants}

# Replace incorrect brand names with the correct ones
test_data["model"] = test_data["model"].replace(replacement_dict)

# Verify the cleaning
print(test_data["model"].unique())

['I30' 'Tiguan' '2 Series' 'Grandland X' '1 Series' 'Fiesta' 'X1'
 'B Class' 'Focus' 'Superb' '5 Series' 'C Class' 'Up' 'Aygo' 'Golf'
 'M Class' 'Land Cruiser' 'TT' 'Adam' 'Zafira' 'E Class' '3 Series' 'IX20'
 'A4' 'Yaris' 'Passat' 'I10' 'Mokka X' 'EcoSport' '4 Series' 'A7' 'Corsa'
 'Kuga' 'Grand C-MAX' 'Q2' 'M4' 'A Class' 'RAV4' 'Fabia' 'Insignia' 'A1'
 'X6' 'Meriva' 'Caravelle' 'Octavia' 'Auris' 'X-CLASS' 'Astra' 'V Class'
 'Polo' 'Karoq' 'Shuttle' 'Mokka' 'Q5' 'Tucson' 'A3' 'SL CLASS' 'Corolla'
 'Ka+' 'X3' 'I40' 'I20' 'Kamiq' nan 'IX35' 'Crossland X' 'Q3' 'Viva'
 'GLA Class' 'CLS Class' 'KA' 'Galaxy' 'X2' 'Kodiaq' 'GLC Class' 'Vivaro'
 'Mondeo' 'Touran' 'CL Class' 'X5' 'Verso' 'Touareg' 'T-Roc' 'Q' 'A5'
 'S Class' 'Scirocco' 'X7' 'B-MAX' '8 Series' 'A6' 'Santa Fe' 'GL Class'
 'GLE Class' 'Beetle' 'X4' 'Golf SV' 'Sharan' 'C-MAX' 'M6' 'A8'
 'CLA Class' 'Kona' 'Citigo' 'Prius' 'Rapid' 'Fusion' 'G Class' 'SLK'
 'Yeti Outdoor' 'Q7' 'C-HR' 'M5' 'T-Cross' 'Avensis' 'Ioniq' 'Amarok' 'Z4'
 '

In [129]:
##correcting spelling mistakes of 'transmission' for test_data

correct_transmission = {
    'Semi-Auto': ['Semi-Aut', 'semi-auto', 'emi-Auto', 'SEMI-AUTO', 'SEMI-AUT', 'EMI-AUTO', 'emi-Aut', 'emi-auto', 'semi-aut'],
    'Manual': ['anual', 'manual', 'Manua', 'MANUAL', ' Manual ', 'ANUAL', 'manua', 'anua', 'MANUA', ' manual ', ' MANUAL ', ' Manual', 'Manual ', 'manual '],
    'Automatic': ['AUTOMATIC', 'automatic', 'Automati', 'utomatic', 'UTOMATIC', 'automati', 'AUTOMATI', 'utomati'],
}

# Create a reverse lookup dictionary (each incorrect form maps to the correct one)
replacement_dict = {variant: correct for correct, variants in correct_transmission.items() for variant in variants}

# Replace incorrect brand names with the correct ones
test_data["transmission"] = test_data["transmission"].replace(replacement_dict)

#replacing the 'unknown' and 'other' variable with a missing value
test_data["transmission"] = test_data["transmission"].replace(['unknow','UNKNOWN','nknown','nknow', 'unknown', 'Other'], np.nan)

# Verify the cleaning
print(test_data["transmission"].unique())

['Automatic' 'Semi-Auto' 'Manual' nan]


In [130]:
##correcting spelling mistakes of 'fuelType' for test_data

correct_fuelType = {
    'Petrol': ['etrol', 'petrol', 'PETROL', 'Petro', 'petro', 'ETROL', 'PETRO', 'etro', 'ETRO'],
    'Diesel': ['diesel','iesel','Diese','DIESEL','DIESE','IESEL','iese','diese','IESE'],
    'Hybrid': ['HYBRID','ybri','Hybri','ybrid','hybrid','YBRID','HYBRI', 'hybri'],
    'Other': ['ther','Othe','OTHER','other']
}

# Create a reverse lookup dictionary (each incorrect form maps to the correct one)
replacement_dict = {variant: correct for correct, variants in correct_fuelType.items() for variant in variants}

# Replace incorrect brand names with the correct ones
test_data["fuelType"] = test_data["fuelType"].replace(replacement_dict)

#replacing the 'other' variable with a missing value 
test_data["fuelType"] = test_data["fuelType"].replace(['ther','Othe','OTHER','other', 'Other'], np.nan)

# Verify the cleaning
print(test_data["fuelType"].unique())

['Petrol' 'Diesel' 'Hybrid' nan 'Electric']


In [131]:
#Check the models of Audi
audi = test_data[test_data['Brand'].str.lower() == 'audi']
unique_audi_models = sorted(audi['model'].dropna().unique())
unique_audi_models

['A',
 'A1',
 'A3',
 'A4',
 'A5',
 'A6',
 'A7',
 'A8',
 'Q',
 'Q2',
 'Q3',
 'Q5',
 'Q7',
 'Q8',
 'R8',
 'RS3',
 'RS4',
 'RS5',
 'RS6',
 'RS7',
 'S3',
 'S4',
 'S5',
 'SQ5',
 'SQ7',
 'TT']

In [132]:
#replacing model 'Q' and 'A' by missing values
test_data.loc[test_data["model"] == 'Q', "model"] = np.nan
test_data.loc[test_data["model"] == 'A', "model"] = np.nan

In [133]:
#Check the models of 'BMW'
BMW = test_data[test_data['Brand'].str.lower() == 'bmw']
unique_bmw_models = sorted(BMW['model'].dropna().unique())
unique_bmw_models

['1 Series',
 '2 Series',
 '2 series',
 '3 Series',
 '4 Series',
 '5 Series',
 '6 Series',
 '7 Series',
 '8 Series',
 'I3',
 'I8',
 'M',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'X',
 'X1',
 'X2',
 'X3',
 'X4',
 'X5',
 'X6',
 'X7',
 'Z3',
 'Z4']

In [134]:
#replacing model 'M' and X' by missing values
test_data.loc[test_data["model"] == 'M', "model"] = np.nan
test_data.loc[test_data["model"] == 'X', "model"] = np.nan

In [135]:
#Check the models of 'Ford'
Ford = test_data[test_data['Brand'].str.lower() == 'ford']
unique_ford_models_v = sorted(Ford['model'].dropna().unique())
unique_ford_models_v

['B-MAX',
 'C-MAX',
 'EDGE',
 'EcoSport',
 'Fiesta',
 'Focus',
 'Fusion',
 'Galaxy',
 'Grand C-MAX',
 'Grand Tourneo Connect',
 'KA',
 'Ka+',
 'Kuga',
 'Mondeo',
 'Mustang',
 'Puma',
 'S-MAX',
 'Tourneo Connect',
 'Tourneo Custom',
 'Transit Tourneo']

In [136]:
#Check the models of 'Hyundai'
Hyundai = test_data[test_data['Brand'].str.lower() == 'hyundai']
unique_hyundai_models = sorted(Hyundai['model'].dropna().unique())
unique_hyundai_models

['A5',
 'I1',
 'I10',
 'I2',
 'I20',
 'I3',
 'I30',
 'I4',
 'I40',
 'I800',
 'IX20',
 'IX35',
 'Ioniq',
 'Kona',
 'Q2',
 'Q3',
 'Santa Fe',
 'Terracan',
 'Tucson',
 'Veloster']

In [137]:
# Replace Hyundai A5 by Audi A5
mask_test = (test_data["Brand"] == "Hyundai") & (test_data["model"] == "A5")
test_data.loc[mask_test, "Brand"] = "Audi"
test_data.loc[mask_test, "model"] = "A5"

# Replace Hyundai Q2 by Audi Q2
mask_test = (test_data["Brand"] == "Hyundai") & (test_data["model"] == "Q2")
test_data.loc[mask_test, "Brand"] = "Audi"
test_data.loc[mask_test, "model"] = "Q2"

# Replace Hyundai Q3 by Audi Q3
mask_test = (test_data["Brand"] == "Hyundai") & (test_data["model"] == "Q3")
test_data.loc[mask_test, "Brand"] = "Audi"
test_data.loc[mask_test, "model"] = "Q3"

In [138]:
#Check the models of 'Mercedes'
Mercedes = test_data[test_data['Brand'].str.lower() == 'mercedes']
unique_mercedes_models = sorted(Mercedes['model'].dropna().unique())
unique_mercedes_models

['180',
 'A Class',
 'B Class',
 'C Class',
 'CL Class',
 'CLA Class',
 'CLC Class',
 'CLK',
 'CLS Class',
 'E Class',
 'G Class',
 'GL Class',
 'GLA Class',
 'GLB Class',
 'GLC Class',
 'GLE Class',
 'GLS Class',
 'M Class',
 'R Class',
 'S Class',
 'SL CLASS',
 'SLK',
 'V Class',
 'X-CLASS']

- In Mercedes, 180 is not a complete model name, they refer only to the engine/variant, not the class or body style. 
- Therefore, we have decided to replace them by missing values. 

In [139]:
#replacing model '180' by missing value
test_data.loc[test_data["model"] == '180', "model"] = np.nan

In [140]:
#Check the models of 'Opel'
Opel = test_data[test_data['Brand'].str.lower() == 'opel']
unique_opel_models = sorted(Opel['model'].dropna().unique())
unique_opel_models

['Adam',
 'Agila',
 'Ampera',
 'Antara',
 'Astra',
 'Cascada',
 'Combo Life',
 'Corsa',
 'Crossland',
 'Crossland X',
 'Grandland',
 'Grandland X',
 'Gtc',
 'Insignia',
 'Meriva',
 'Mokka',
 'Mokka X',
 'Tigra',
 'Vectra',
 'Viva',
 'Vivaro',
 'Zafira',
 'Zafira Tourer']

- All the models showed seem to correspond to the brand 'Opel'. 

In [141]:
#Check the models of 'Skoda'
Skoda = test_data[test_data['Brand'].str.lower() == 'skoda']
unique_skoda_models = sorted(Skoda['model'].dropna().unique())
unique_skoda_models

['Citigo',
 'Fabia',
 'Kamiq',
 'Karoq',
 'Kodiaq',
 'Octavia',
 'Rapid',
 'Roomster',
 'Scala',
 'Superb',
 'Yeti',
 'Yeti Outdoor']

- All the models showed seem to correspond to the brand 'Skoda'. 

In [142]:
#Check the models of 'VW'
VW = test_data[test_data['Brand'].str.lower() == 'vw']
unique_vw_models = sorted(VW['model'].dropna().unique())
unique_vw_models

['Amarok',
 'Arteon',
 'Beetle',
 'CC',
 'Caddy Life',
 'Caddy Maxi Life',
 'California',
 'Caravelle',
 'Eos',
 'Fox',
 'Golf',
 'Golf S',
 'Golf SV',
 'Jetta',
 'Passat',
 'Polo',
 'Scirocco',
 'Shara',
 'Sharan',
 'Shuttle',
 'T-Cross',
 'T-Roc',
 'Tiguan',
 'Tiguan Allspace',
 'Touareg',
 'Touran',
 'Up']

- 'Shara' is not the right VW model, the correct would be 'Sharan'. 

In [143]:
#replacing 'Shara' by the correct name 
test_data.loc[test_data["model"] == 'Shara', "model"] = 'Sharan'

In [144]:
#checking negative values 
test_data[test_data['previousOwners'] < 0]['previousOwners']

carID
104574    -2
102304    -2
78379     -2
76435     -2
76702     -2
          ..
95465     -2
86894     -2
98334     -2
107094    -2
103453    -2
Name: previousOwners, Length: 168, dtype: Int32

In [145]:
#replacing the negative values by their module.
test_data['previousOwners'] = test_data['previousOwners'].replace(-2, 2)

In [146]:
#checking negative observations 
test_data[test_data['mileage'] < 0]

Brand    model  year transmission       mileage fuelType    tax  \
carID                                                                        
106581        VW   Tiguan  2017    Semi-Auto -48190.655673   Petrol  150.0   
92673   Mercedes  C Class  2017          NaN -50755.210230   Diesel    NaN   
93065   Mercedes  C Class  2019    Semi-Auto -50755.210230   Petrol    NaN   
89444    Hyundai   Tucson  2020    Semi-Auto -36635.042697   Hybrid  150.0   
85269       Ford   Mondeo  2017    Automatic -42650.453719   Diesel   20.0   
...          ...      ...   ...          ...           ...      ...    ...   
100676      Opel  Cascada  2015       Manual -42707.564215   Diesel  125.0   
92455   Mercedes  C Class  2019    Semi-Auto -50755.210230   Petrol    NaN   
106053        VW     Polo  2017       Manual -48190.655673   Petrol   20.0   
95430   Mercedes  A Class  2016       Manual -50755.210230   Petrol  125.0   
91768   Mercedes  A Class  2019       Manual -50755.210230   Petrol  145.0   

         mpg  engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                               
106581  38.2         2.0           60.0               2          0  
92673    NaN         2.1           93.0               2          0  
93065    NaN         3.0           97.0               4          0  
89444   50.4         1.6           41.0               0          0  
85269   67.3         2.0           31.0               0          0  
...      ...         ...            ...             ...        ...  
100676  57.6         2.0           77.0               2          0  
92455    NaN         2.0           59.0               2          0  
106053  58.9         1.0           72.0               4          0  
95430   51.4         1.6           58.0               1          0  
91768   28.5         1.3           81.0               1          0  

[170 rows x 12 columns]

In [147]:
#replacing negative values by missing values 
test_data.loc[test_data["mileage"] < 0, "mileage"] = np.nan

In [148]:
#checking negative observations 
test_data[test_data['mpg'] < 0]

Brand     model  year transmission  mileage fuelType         tax  \
carID                                                                    
79461   BMW  5 Series  2016    Automatic  83189.0   Diesel   20.000000   
81976   BMW  3 Series  2019    Semi-Auto   6000.0   Diesel  145.000000   
80175   BMW        X1  2016       Manual      NaN   Diesel   20.000000   
80445   BMW  1 Series  2015       Manual  46000.0   Petrol  125.000000   
79366   BMW        X3  2015    Semi-Auto  44126.0   Diesel  200.000000   
82248   BMW  5 Series  2019    Semi-Auto   5130.0   Diesel  145.000000   
80677   BMW  1 Series  2015    Semi-Auto  46242.0   Diesel   30.000000   
79287   BMW  3 Series  2019    Semi-Auto  23000.0   Petrol  150.000000   
82168   BMW  3 Series  2016       Manual  27796.0   Petrol  205.000000   
80535   BMW  5 Series  2017    Semi-Auto  20279.0      NaN  135.000000   
81821   BMW        X1  2017       Manual  33600.0      NaN  150.000000   
80414   BMW  3 Series  2019    Semi-Auto   7004.0   Petrol  145.000000   
81353   BMW  2 Series  2017    Semi-Auto  30330.0   Diesel  145.000000   
82185   BMW  6 Series  2015    Semi-Auto  51412.0   Diesel  160.000000   
81132   BMW  3 Series  2015    Automatic  50000.0   Diesel  316.487189   
80965   BMW        X1  2017    Automatic  89232.0   Diesel  145.000000   
80270   BMW  3 Series  2019    Automatic   1000.0   Diesel  145.000000   

             mpg  engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                                   
79461 -43.421768    2.000000           68.0               2          0  
81976 -43.421768    3.822758           86.0               1          0  
80175 -43.421768    2.000000           32.0               0          0  
80445 -43.421768    1.500000           54.0               0          0  
79366 -43.421768    3.000000           79.0               3          0  
82248 -43.421768    2.000000           41.0               4          0  
80677 -43.421768    2.000000           74.0               0          0  
79287 -43.421768    2.000000           41.0               2          0  
82168 -43.421768    2.000000           97.0               2          0  
80535 -43.421768    2.000000           91.0               3          0  
81821 -43.421768    2.000000           61.0               0          0  
80414 -43.421768    2.000000           98.0               3          0  
81353 -43.421768    2.000000           52.0               1          0  
82185 -43.421768    3.000000           33.0               0          0  
81132 -43.421768    3.000000           87.0               4          0  
80965 -43.421768    2.000000           94.0               0          0  
80270 -43.421768    2.000000           48.0               1          0

In [149]:
#replacing negative values by missing values 
test_data.loc[test_data["mpg"] < 0, "mpg"] = np.nan

In [150]:
#checking the observation where the car is electric
test_data[test_data['fuelType'] == 'Electric']

Brand model  year transmission  mileage  fuelType    tax    mpg  \
carID                                                                   
79316   BMW    I3  2017    Automatic  20321.0  Electric  135.0  470.8   

       engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                        
79316         0.0           90.0               3          0

In [151]:
#setting the mpg of electric cars to 0
test_data.loc[test_data['fuelType'] == 'Electric', 'mpg'] = 0

In [152]:
#checking obervations where mpg is lower than 0.5 
test_data[test_data['engineSize'] < 0.5]

Brand     model  year transmission  mileage  fuelType    tax   mpg  \
carID                                                                           
103242      Opel     Astra  2018       Manual  32976.0    Petrol  145.0  51.4   
86916       Ford    Fiesta  2017       Manual  32320.0    Petrol    0.0  65.7   
96518      Skoda   Octavia  2018       Manual  18822.0    Diesel  145.0  68.9   
80066        BMW        M6  2016    Semi-Auto  26642.0    Petrol  555.0  28.5   
105787        VW      Polo  2018       Manual  15055.0    Petrol  150.0  64.2   
...          ...       ...   ...          ...      ...       ...    ...   ...   
79316        BMW        I3  2017    Automatic  20321.0  Electric  135.0   0.0   
89380       Ford    Fiesta  2018       Manual  10573.0    Petrol  150.0  65.7   
92869   Mercedes       NaN  2019    Semi-Auto   4631.0    Diesel    NaN   NaN   
80615        NaN  3 Series  2020    Semi-Auto      NaN    Diesel  145.0  51.4   
89904    Hyundai       I40  2015       Manual  13268.0    Diesel   30.0  65.7   

        engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                         
103242    0.000000           56.0               1          0  
86916    -0.103493           54.0               2          0  
96518     0.191462           32.0               0          0  
80066     0.313407           83.0               1          0  
105787    0.186425           36.0               1          0  
...            ...            ...             ...        ...  
79316     0.000000           90.0               3          0  
89380    -0.103493           49.0               4          0  
92869     0.307074           86.0               2          0  
80615     0.313407           85.0               1          0  
89904     0.000000           36.0               2          0  

[226 rows x 12 columns]

In [153]:
#replacing negative values by missing values 
test_data.loc[test_data["engineSize"] < 0, "engineSize"] = np.nan

In [154]:
#checking negative observations 
test_data[test_data['tax'] < 0]

Brand     model  year transmission  mileage fuelType        tax  \
carID                                                                        
91338   Mercedes   E Class  2019    Automatic   6458.0   Petrol -56.193202   
107819        VW    Amarok  2019    Automatic   3655.0   Diesel -49.153541   
82836       Ford    Fiesta  2018          NaN   9358.0   Petrol -45.780610   
84840       Ford      Kuga  2015       Manual  42277.0   Diesel -45.780610   
81080        BMW        X5  2019    Semi-Auto   3658.0   Diesel -43.242082   
...          ...       ...   ...          ...      ...      ...        ...   
87489       Ford     Focus  2018       Manual  13861.0   Diesel -45.780610   
94498   Mercedes  CL Class  2013       Manual  69965.0   Petrol -56.193202   
86620       Ford    Fiesta  2017       Manual      NaN   Petrol -45.780610   
97807      Skoda     Fabia  2019       Manual     10.0   Petrol -18.330743   
87336       Ford    Mondeo  2016       Manual  27127.0   Diesel -45.780610   

         mpg  engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                               
91338   32.1         4.0           49.0               3          0  
107819  33.6         3.0           97.0               4          0  
82836   65.7         1.0           66.0            <NA>          0  
84840   60.1         2.0           86.0               2          0  
81080   37.7         3.0            NaN               1          0  
...      ...         ...            ...             ...        ...  
87489   74.3         1.5           48.0               0          0  
94498   50.4         1.6           78.0               3          0  
86620   54.3         1.2           38.0               3          0  
97807   51.4         1.0           78.0               0       <NA>  
87336   65.7         1.5           44.0               0          0  

[161 rows x 12 columns]

In [155]:
#replacing negative values by missing values 
test_data.loc[test_data["tax"] < 0, "tax"] = np.nan

In [156]:
#checking values higher than 100 
test_data[test_data['paintQuality%'] > 100]

Brand     model  year transmission  mileage fuelType    tax   mpg  \
carID                                                                          
82849       Ford  EcoSport  2017       Manual  12055.0   Petrol  125.0  53.3   
102729      Opel     Astra  2016          NaN  25873.0   Petrol  125.0  50.4   
89325       Ford    Fiesta  2016       Manual  17810.0   Petrol   20.0  62.8   
78622       Audi        A4  2016       Manual  35080.0   Diesel    0.0  74.3   
81359        BMW  3 Series  2016    Automatic  40128.0   Diesel   30.0  64.2   
...          ...       ...   ...          ...      ...      ...    ...   ...   
88134       Ford       NaN  2014       Manual  44720.0   Petrol    0.0  65.7   
76826       Audi        Q3  2024    Semi-Auto  35117.0   Diesel  160.0  50.4   
76163       Audi        A3  2020    Semi-Auto   2500.0   Petrol  145.0  43.5   
93220   Mercedes   C Class  2019    Automatic  11890.0   Diesel    NaN   NaN   
78406       Audi        A6  2015    Automatic  31224.0      NaN  160.0  50.4   

        engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                         
82849          1.0     125.109951               3          0  
102729         1.4     125.003773               0       <NA>  
89325          1.0     125.109951               0          0  
78622          2.0     125.301945               4          0  
81359          2.0     125.569499               4          0  
...            ...            ...             ...        ...  
88134          1.0     125.109951               3          0  
76826          2.0     125.301945               2          0  
76163          NaN     125.301945               4          0  
93220          1.6     125.202033            <NA>          0  
78406          3.0     125.301945               2          0  

[168 rows x 12 columns]

In [157]:
#replacing values higher than 100 by missing values 
test_data.loc[test_data["paintQuality%"] > 100, "paintQuality%"] = np.nan

In [158]:
#checking values higher than 2020 
test_data[test_data['year'] > 2020]

Brand     model  year transmission  mileage fuelType    tax   mpg  \
carID                                                                          
89856    Hyundai       I30  2023    Automatic  30700.0   Petrol  205.0  41.5   
101603      Opel    Zafira  2023       Manual  26856.0   Petrol  200.0  41.5   
81259        BMW  4 Series  2024    Semi-Auto   7208.0   Diesel  145.0  65.7   
81832        BMW        X5  2024    Automatic  47000.0   Diesel  200.0  47.1   
100383      Opel   Mokka X  2023       Manual  19094.0   Petrol  145.0  39.2   
...          ...       ...   ...          ...      ...      ...    ...   ...   
94357   Mercedes   E Class  2024    Semi-Auto  48976.0   Diesel    NaN  57.7   
106447        VW    Passat  2023    Semi-Auto   4801.0   Petrol  145.0  41.5   
100025      Opel  Insignia  2023       Manual  19615.0   Diesel  125.0  60.1   
76826       Audi        Q3  2024    Semi-Auto  35117.0   Diesel  160.0  50.4   
103740      Opel     Astra  2023       Manual      NaN   Petrol  160.0  44.8   

        engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                         
89856          1.6           61.0               3          0  
101603         1.4           75.0               2          0  
81259          2.0           62.0               3          0  
81832          3.0           57.0               2          0  
100383         1.4           54.0            <NA>          0  
...            ...            ...             ...        ...  
94357          2.1           32.0               3          0  
106447         1.5           58.0               1          0  
100025         2.0           68.0               0          0  
76826          2.0            NaN               2          0  
103740         1.6           40.0               3          0  

[180 rows x 12 columns]

In [159]:
#replacing years after 2020 by missing values 
test_data.loc[test_data["year"] > 2020, "year"] = np.nan

#### Treating Outliers

In [160]:
test_data[test_data['mileage'] > 150000]

Brand      model  year transmission   mileage fuelType    tax  \
carID                                                                      
78147       Audi         Q5  2011       Manual  168017.0   Diesel  200.0   
91517   Mercedes    C Class  2006    Automatic  153000.0   Petrol  300.0   
102018      Opel      Astra  2001       Manual  159000.0   Petrol  235.0   
81844        BMW   5 Series  2010    Automatic  164500.0   Diesel  140.0   
94627   Mercedes    C Class  1991    Automatic  170000.0   Petrol    NaN   
100290      Opel     Zafira  2013       Manual  279000.0   Diesel  150.0   
80858        BMW   5 Series  2013    Automatic  178987.0   Hybrid  190.0   
106256        VW  Caravelle  2006       Manual  178000.0   Diesel  325.0   
80355        BMW   3 Series  2011       Manual  190000.0   Diesel   20.0   
79846        BMW   3 Series  2014    Automatic  155790.0   Diesel  145.0   
94225   Mercedes    E Class  2014    Automatic  152280.0   Diesel   30.0   
106117       NaN     Passat  2011       Manual  176000.0   Diesel  125.0   
86911       Ford     Mondeo  2011       Manual  151000.0   Diesel   30.0   
108426        VW       Golf  2004       Manual  170000.0   Diesel  165.0   

              mpg  engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                                    
78147    42.10000         2.0           97.0               0          0  
91517    33.60000         1.8           84.0               3          0  
102018   40.40000         1.6           91.0               4          0  
81844    53.30000         2.0           68.0               3          0  
94627         NaN         3.0           56.0               4          0  
100290   55.40000         1.7           81.0               3          0  
80858    40.40000         3.0           88.0               3          0  
106256   34.40000         2.5           67.0               0          0  
80355    68.90000         2.0           50.0               0          0  
79846   151.04181         3.0           85.0               0          0  
94225    58.90000         2.1           47.0               3          0  
106117   60.10000         2.0           38.0               1       <NA>  
86911    65.70000         1.6           30.0               4          0  
108426   52.30000         NaN           85.0               4          0

In [161]:
# Cap milage: replacing all numbers above 150000 by 150000
test_data["mileage"] = test_data["mileage"].clip(lower=0, upper=150000)

In [162]:
test_data[test_data['tax'] > 350]

Brand      model  year transmission        mileage fuelType    tax  \
carID                                                                           
95966   Mercedes    S Class  2011    Automatic   66000.000000   Petrol  570.0   
94732   Mercedes    S Class  2015    Automatic   23156.000000   Petrol  555.0   
80066        BMW         M6  2016    Semi-Auto   26642.000000   Petrol  555.0   
79095       Audi         A8  2015    Automatic   30306.000000   Petrol  570.0   
80790        BMW         M5  <NA>    Automatic   55241.000000   Petrol  555.0   
79753        BMW         M5  2015    Semi-Auto   42932.000000   Petrol  555.0   
78115       Audi         A8  2017    Automatic   16975.000000   Petrol  555.0   
103312      Opel   Insignia  2012       Manual   48490.000000   Petrol  555.0   
95550   Mercedes   SL CLASS  2016    Automatic   19425.000000      NaN  555.0   
92738   Mercedes  CLS Class  2012    Automatic   46283.000000   Petrol  555.0   
91008   Mercedes   GL Class  2014    Automatic   55000.000000   Petrol  570.0   
81300        BMW         M5  2016    Semi-Auto   25780.000000   Petrol  565.0   
95730   Mercedes   SL CLASS  2014    Semi-Auto   86705.854885   Petrol  565.0   
95907   Mercedes  GLE Class  2015    Automatic   13340.000000   Petrol  570.0   
78458       Audi        RS5  2015    Automatic   66000.000000   Petrol  555.0   
76238       Audi         R8  2007    Automatic   39000.000000   Petrol  515.0   
78064       Audi         R8  2016    Semi-Auto   10172.000000   Petrol  570.0   
79951        BMW         M6  2016    Semi-Auto   19000.000000   Petrol  555.0   
94338   Mercedes    C Class  2013    Semi-Auto   43442.000000   Petrol  580.0   
79988        BMW         M5  2012    Automatic   51000.000000   Petrol  555.0   
80032        BMW         M6  2015    Automatic            NaN   Petrol  555.0   
80483        BMW   5 Series  2010    Automatic   55000.000000   Petrol  555.0   
92442   Mercedes    M Class  2010    Automatic  106800.000000   Diesel  555.0   
94467   Mercedes    R Class  2007    Automatic   60000.000000   Diesel  565.0   
76412       Audi        RS6  2015    Automatic   28123.000000   Petrol  555.0   
92966   Mercedes   SL CLASS  <NA>    Automatic   56098.000000   Petrol  555.0   
87010       Ford       Kuga  2011       Manual   56000.000000   Petrol  555.0   
95180   Mercedes    S Class  2016    Semi-Auto   25317.000000   Petrol  570.0   
93937   Mercedes    S Class  2002    Automatic   24000.000000   Petrol  570.0   
78926       Audi         Q7  <NA>    Semi-Auto   34000.000000   Diesel  555.0   
81891        BMW         M3  2010       Manual   79000.000000   Petrol  570.0   
79634        BMW         X3  2007    Automatic  100000.000000   Diesel  555.0   
80874        BMW         M6  2015    Semi-Auto   34017.000000   Petrol  555.0   
92367   Mercedes    E Class  2015    Automatic   40988.000000   Petrol  565.0   
91988   Mercedes    M Class  2011    Automatic   90000.000000   Diesel  555.0   
79665        BMW         M3  2013    Semi-Auto   30500.000000   Petrol  570.0   
93078   Mercedes   SL CLASS  2010    Automatic   32450.000000   Petrol  540.0   
77588       Audi        RS7  2014    Automatic   56000.000000   Petrol  555.0   
92427   Mercedes        SLK  2006    Automatic   65000.000000   Petrol  565.0   
82098        BMW         M6  2014          NaN   34000.000000   Petrol  565.0   
79082       Audi        RS4  2014    Semi-Auto   58460.000000   Petrol  555.0   
77758       Audi         TT  2007       Manual   63000.000000   Petrol  555.0   
81467        BMW         M3  2009       Manual            NaN   Petrol  580.0   
94134   Mercedes   SL CLASS  2007    Automatic   45000.000000   Petrol  570.0   
93366   Mercedes    M Class  2015    Semi-Auto   43910.000000   Petrol  570.0   
79044       Audi        RS4  2014    Semi-Auto            NaN   Petrol  555.0   
86187       Ford      S-MAX  2008    Automatic  106000.000000   Petrol  555.0   
92550   Mercedes    M Class  2011    Autom

In [163]:
# Cap tax: replacing all numbers above 350 by 350
test_data["tax"] = test_data["tax"].clip(lower=0, upper=350)

In [164]:
test_data[test_data['mpg'] > 300]

Brand model  year transmission  mileage fuelType    tax    mpg  \
carID                                                                  
80758   BMW    I3  2016    Automatic  59945.0   Hybrid    0.0  470.8   
80669   BMW    I3  2017    Automatic  28169.0   Hybrid    0.0  470.8   
80184   BMW    I3  2017    Automatic  41949.0   Hybrid  140.0  470.8   
81032   BMW    I3  2017    Automatic  33021.0   Hybrid    0.0  470.8   
79921   BMW    I3  2017    Automatic  50867.0      NaN  135.0  470.8   
82073   BMW    I3  2015    Automatic  59000.0      NaN    0.0  470.8   
80882   BMW    I3  2017    Automatic  10900.0   Hybrid  140.0  470.8   
80277   BMW    I3  2017    Automatic  26139.0   Hybrid  135.0  470.8   
79191   BMW    I3  2017    Automatic  17338.0   Hybrid  135.0  470.8   
82186   BMW    I3  2017    Automatic   3976.0   Hybrid  135.0  470.8   
81546   BMW    I3  2017    Automatic  22063.0   Hybrid    0.0  470.8   
82309   BMW    I3  2014    Automatic  37161.0   Hybrid    0.0  470.8   
81592   BMW    I3  2017    Automatic  20082.0   Hybrid  135.0  470.8   
79991   BMW    I3  2015    Automatic  79830.0   Hybrid    0.0  470.8   
81415   BMW    I3  2016    Automatic  68000.0   Hybrid    0.0  470.8   
82238   BMW    I3  2017    Automatic  19178.0      NaN    0.0  470.8   

       engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                        
80758    0.000000           66.0               3          0  
80669    0.000000           52.0               3          0  
80184    0.000000           37.0               4          0  
81032         NaN           44.0               3          0  
79921    0.600000           48.0               2          0  
82073    0.600000           86.0               1          0  
80882    0.000000           78.0               2          0  
80277    0.000000           84.0               2          0  
79191    0.000000           47.0               0          0  
82186    0.000000           45.0               2          0  
81546    0.000000           94.0               3          0  
82309    0.000000           73.0               1          0  
81592    0.000000           76.0               4          0  
79991    0.000000           41.0               4          0  
81415    3.822758           32.0               4          0  
82238    0.600000           43.0               0          0

In [165]:
# Cap mpg: replacing all numbers above 300 by 300
test_data["mpg"] = test_data["mpg"].clip(lower=0, upper=300)

In [166]:
test_data[test_data['engineSize'] > 5]

Brand      model  year transmission       mileage fuelType    tax  \
carID                                                                         
94732  Mercedes    S Class  2015    Automatic  23156.000000   Petrol  350.0   
79095      Audi         A8  2015    Automatic  30306.000000   Petrol  350.0   
95550  Mercedes   SL CLASS  2016    Automatic  19425.000000      NaN  350.0   
92738  Mercedes  CLS Class  2012    Automatic  46283.000000   Petrol  350.0   
91008  Mercedes   GL Class  2014    Automatic  55000.000000   Petrol  350.0   
76804      Audi         R8  2020    Semi-Auto    333.000000   Petrol  145.0   
94754  Mercedes    C Class  2013    Automatic  41866.000000   Petrol    NaN   
77563      Audi         R8  2019    Automatic  11936.000000   Petrol  145.0   
95730  Mercedes   SL CLASS  2014    Semi-Auto  86705.854885   Petrol  350.0   
95907  Mercedes  GLE Class  2015    Automatic  13340.000000   Petrol  350.0   
93551  Mercedes  GLE Class  2019    Automatic   2704.000000   Petrol  145.0   
78064      Audi         R8  2016    Semi-Auto  10172.000000   Petrol  350.0   
94338  Mercedes    C Class  2013    Semi-Auto  43442.000000   Petrol  350.0   
92587  Mercedes   SL CLASS  2019    Automatic    150.000000   Petrol  145.0   
77682      Audi         R8  2019    Automatic           NaN   Petrol  150.0   
91924  Mercedes    C Class  2006    Automatic  63000.000000   Petrol    NaN   
95180  Mercedes    S Class  2016    Semi-Auto  25317.000000   Petrol  350.0   
92367  Mercedes    E Class  2015    Automatic  40988.000000   Petrol  350.0   
93716  Mercedes    S Class  2017    Semi-Auto  15400.000000   Petrol  145.0   
76838      Audi         R8  2019    Automatic   2369.000000   Petrol  145.0   
93123  Mercedes  GLS Class  2018    Semi-Auto  41102.000000   Petrol  145.0   
81532       BMW   7 Series  2017    Automatic  22000.000000   Petrol  150.0   
93366  Mercedes    M Class  2015    Semi-Auto  43910.000000   Petrol  350.0   
76653      Audi         R8  2018    Automatic   3562.000000   Petrol  145.0   

        mpg  engineSize  paintQuality%  previousOwners  hasDamage  
carID                                                              
94732  28.0         5.5      54.000000               2          0  
79095  25.0         6.3      65.000000               2          0  
95550   NaN         5.5      83.000000               0          0  
92738  28.5         5.5      48.000000               3          0  
91008  23.0         5.5      73.000000               4       <NA>  
76804  21.4         5.2      31.000000               1          0  
94754   NaN         6.2      47.000000               1          0  
77563  21.4         5.2      70.000000               0          0  
95730  28.5         5.5      40.000000               3          0  
95907  23.9         5.5      64.000000               0          0  
93551  23.7         5.5      41.000000               3          0  
78064  24.8         5.2      34.000000               0          0  
94338  23.0         6.2      39.000000               0          0  
92587  28.0         5.5       3.207418               3          0  
77682  21.4         5.2      57.000000               1          0  
91924   NaN         5.4      89.000000               2          0  
95180  24.1         6.0      41.000000               3          0  
92367  29.1         5.5      80.000000               2          0  
93716  28.0         5.5      72.000000               3          0  
76838  22.6         5.2            NaN               0          0  
93123  23.0         5.5      43.000000               0          0  
81532  22.1         6.6      56.000000               0          0  
93366  23.9         5.5      68.000000               4          0  
76653  23.0         5.2      66.000000               4          0

In [167]:
# Cap engineSize: replacing all numbers above 5 by 5
test_data["engineSize"] = test_data["engineSize"].clip(lower=0, upper=5)

#### Filling Missing Values

In [168]:
test_data[metric_features].isna().sum().sort_values(ascending=False)

tax               3469
mpg               3305
mileage            859
year               833
paintQuality%      793
engineSize         661
previousOwners     597
hasDamage          597
dtype: int64

In [169]:
#scalling X_train and X_val since KNN imputer uses distances

#numerical variables whose missing values need to be filled
numeric_cols = ['tax', 'mpg', 'mileage', 'paintQuality%', 'engineSize', 'hasDamage', 'previousOwners', 'year']
scaler = MinMaxScaler()

# fitting the scaler only on training dataset (to avoid leakage)
test_data[numeric_cols] = scaler.fit_transform(test_data[numeric_cols])

In [170]:
knn = KNNImputer(n_neighbors=5, weights='distance')

test_data[numeric_cols] = knn.fit_transform(test_data[numeric_cols])

In [171]:
test_data[metric_features].isna().sum().sort_values(ascending=False)

year              0
mileage           0
tax               0
mpg               0
engineSize        0
paintQuality%     0
previousOwners    0
hasDamage         0
dtype: int64

In [172]:
test_data[non_metric_features].isna().sum().sort_values(ascending=False)

transmission    971
fuelType        738
model           713
Brand           649
dtype: int64

In [173]:
cat_imputer = SimpleImputer(strategy='most_frequent')

test_data.loc[:, non_metric_features] = cat_imputer.fit_transform(test_data[non_metric_features])

In [174]:
test_data[non_metric_features].isna().sum().sort_values(ascending=False)

Brand           0
model           0
transmission    0
fuelType        0
dtype: int64

#### Feature Engineering 

In [175]:
test_data['engineEfficiency'] = test_data['mpg'] / test_data['engineSize']

In [176]:
freq_encoding_brand = test_data['Brand'].value_counts()
test_data['brand_encoded'] = test_data['Brand'].map(freq_encoding_brand)

In [177]:
freq_encoding_model = test_data['model'].value_counts()
test_data['model_encoded'] = test_data['model'].map(freq_encoding_model)

In [178]:
test_data = pd.get_dummies(test_data, columns=['transmission'], prefix='Transmission', drop_first=True)

In [179]:
print(test_data["fuelType"].value_counts())

fuelType
Petrol      18235
Diesel      13395
Hybrid        936
Electric        1
Name: count, dtype: int64


In [180]:
rare_fuels = ['Electric', 'Other']
test_data['fuelType'] = test_data['fuelType'].replace(rare_fuels, 'Other')

test_data = pd.get_dummies(test_data, columns=['fuelType'], prefix='Fuel', drop_first=True)

In [181]:
test_data.isna().sum().sort_values(ascending=False)

engineEfficiency          1
Brand                     0
model                     0
year                      0
tax                       0
mileage                   0
engineSize                0
paintQuality%             0
previousOwners            0
mpg                       0
hasDamage                 0
brand_encoded             0
model_encoded             0
Transmission_Manual       0
Transmission_Semi-Auto    0
Fuel_Hybrid               0
Fuel_Other                0
Fuel_Petrol               0
dtype: int64

In [182]:
mean_freq = freq_encoding_model.mean()
test_data['engineEfficiency'] = test_data['engineEfficiency'].map(freq_encoding_model).fillna(mean_freq)

In [183]:
test_data.isna().sum().sort_values(ascending=False)

Brand                     0
model                     0
year                      0
mileage                   0
tax                       0
mpg                       0
engineSize                0
paintQuality%             0
previousOwners            0
hasDamage                 0
engineEfficiency          0
brand_encoded             0
model_encoded             0
Transmission_Manual       0
Transmission_Semi-Auto    0
Fuel_Hybrid               0
Fuel_Other                0
Fuel_Petrol               0
dtype: int64

In [184]:
test_data = test_data.drop(['Brand', 'model'], axis=1)

In [1]:
'''scaler = MinMaxScaler()

scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train) 
X_val_scaled = scaler.transform(X_val)

X_train_scaled = pd.DataFrame(X_train_scaled, columns = X_train.columns).set_index(X_train.index)
X_val_scaled = pd.DataFrame(X_val_scaled, columns = X_val.columns).set_index(X_val.index)

X_train = X_train_scaled
X_val = X_val_scaled

# ensuring that y_train has the same rows X_train
y_train = y_train.loc[X_train.index]
y_val = y_val.loc[X_val.index]

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)'''

'scaler = MinMaxScaler()\n\nscaler.fit(X_train)\n\nX_train_scaled = scaler.transform(X_train) \nX_val_scaled = scaler.transform(X_val)\n\nX_train_scaled = pd.DataFrame(X_train_scaled, columns = X_train.columns).set_index(X_train.index)\nX_val_scaled = pd.DataFrame(X_val_scaled, columns = X_val.columns).set_index(X_val.index)\n\nX_train = X_train_scaled\nX_val = X_val_scaled\n\n# ensuring that y_train has the same rows X_train\ny_train = y_train.loc[X_train.index]\ny_val = y_val.loc[X_val.index]\n\nprint("X_train shape:", X_train.shape)\nprint("y_train shape:", y_train.shape)'

#### Feature Selection

##### Sequential feature selection

In [185]:
from sklearn.linear_model import Ridge
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.model_selection import PredefinedSplit

In [186]:
# Combine train and validation datasets
X_combined = np.concatenate([X_train, X_val])
y_combined = np.concatenate([y_train, y_val])

# Create a test fold index (-1 for train, 0 for validation)
test_fold = [-1] * len(X_train) + [0] * len(X_val)

print('Test fold: ', len(test_fold))
print('X_combined: ', len(X_combined))
print('y_combined: ', len(y_combined))

# Define the PredefinedSplit
ps = PredefinedSplit(test_fold=test_fold)

Test fold:  74111
X_combined:  74111
y_combined:  74111


##### Ridge

In [186]:
base_estimator1 = Ridge(alpha=1.0, random_state=0)

In [188]:
sfs_forward = SequentialFeatureSelector(
    estimator=base_estimator1,
    n_features_to_select="auto",   # Let SFS find optimal count
    direction="forward",
    scoring="neg_mean_squared_error",
    cv=5,                          # small CV to reduce compute
    n_jobs=-1
)

sfs_forward.fit(X_train, y_train)

# Selected feature mask and names
forward_mask = sfs_forward.get_support()
forward_features = X_train.columns[forward_mask]

print("Forward Selected Features:")
print(list(forward_features))

# Evaluate on validation set
base_estimator1.fit(X_train[forward_features], y_train)
y_val_pred_forward = base_estimator1.predict(X_val[forward_features])
val_rmse_forward = np.sqrt(mean_squared_error(y_val, y_val_pred_forward))

print("Validation RMSE (Forward SFS):", val_rmse_forward)

Forward Selected Features:
['year', 'mileage', 'mpg', 'engineSize', 'engineEfficiency', 'Transmission_Manual', 'Transmission_Semi-Auto', 'Fuel_Hybrid']
Validation RMSE (Forward SFS): 5062.115861954206


In [189]:
sfs_backward = SequentialFeatureSelector(
    estimator=base_estimator1,
    n_features_to_select="auto",
    direction="backward",
    scoring="neg_mean_squared_error",
    cv=5,
    n_jobs=-1,
)

sfs_backward.fit(X_train, y_train)

# Selected feature mask and names
backward_mask = sfs_backward.get_support()
backward_features = X_train.columns[backward_mask]

print("Backward Selected Features:")
print(list(backward_features))

# Evaluate on validation set
base_estimator1.fit(X_train[backward_features], y_train)
y_val_pred_backward = base_estimator1.predict(X_val[backward_features])
val_rmse_backward = np.sqrt(mean_squared_error(y_val, y_val_pred_backward))

print("Validation RMSE (Backward SFS):", val_rmse_backward)

Backward Selected Features:
['year', 'mileage', 'mpg', 'engineSize', 'engineEfficiency', 'Transmission_Manual', 'Transmission_Semi-Auto', 'Fuel_Hybrid']
Validation RMSE (Backward SFS): 5062.115861954206


##### Random Forrest

In [188]:
base_estimator2 = RandomForestRegressor(
    n_estimators=100,   # number of trees
    max_depth=8,
    min_samples_leaf = 4,
    max_features="sqrt",
    random_state=0,
    n_jobs=-1
)

In [193]:
sfs_forward = SequentialFeatureSelector(
    estimator=base_estimator2,
    n_features_to_select="auto",   # Let SFS find optimal count
    direction="forward",
    scoring="neg_mean_squared_error",
    cv=ps,                          # small CV to reduce compute
    n_jobs=-1,
    tol=1e-3  
)

sfs_forward.fit(X_combined, y_combined)

# Selected feature mask and names
forward_mask = sfs_forward.get_support()
forward_features = X_train.columns[forward_mask]

print("Forward Selected Features:")
print(list(forward_features))

# Evaluate on validation set
base_estimator2.fit(X_train[forward_features], y_train)
y_val_pred_forward = base_estimator2.predict(X_val[forward_features])
val_rmse_forward = np.sqrt(mean_squared_error(y_val, y_val_pred_forward))

print("Validation RMSE (Forward SFS):", val_rmse_forward)

KeyboardInterrupt: 

In [ ]:
sfs_backward = SequentialFeatureSelector(
    estimator=base_estimator2,
    n_features_to_select="auto",
    direction="backward",
    scoring="neg_mean_squared_error",
    cv=ps,
    n_jobs=-1,
    tol=1e-3  
)

sfs_backward.fit(X_combined, y_combined)

# Selected feature mask and names
backward_mask = sfs_backward.get_support()
backward_features = X_train.columns[backward_mask]

print("Backward Selected Features:")
print(list(backward_features))

# Evaluate on validation set
base_estimator2.fit(X_train[backward_features], y_train)
y_val_pred_backward = base_estimator2.predict(X_val[backward_features])
val_rmse_backward = np.sqrt(mean_squared_error(y_val, y_val_pred_backward))

print("Validation RMSE (Backward SFS):", val_rmse_backward)

##### Neural Network

In [194]:
from sklearn.neural_network import MLPRegressor
base_estimator3 = MLPRegressor(
    hidden_layer_sizes=(17, 7),
    solver='adam',
    learning_rate_init=0.001,
    max_iter=200,
    random_state=0
)

In [195]:
sfs_forward = SequentialFeatureSelector(
    estimator=base_estimator3,
    n_features_to_select="auto",   # Let SFS find optimal count
    direction="forward",
    scoring="neg_mean_squared_error",
    cv=5,                          # small CV to reduce compute
    n_jobs=-1
)

sfs_forward.fit(X_train, y_train)

# Selected feature mask and names
forward_mask = sfs_forward.get_support()
forward_features = X_train.columns[forward_mask]

print("Forward Selected Features:")
print(list(forward_features))

# Evaluate on validation set
base_estimator3.fit(X_train[forward_features], y_train)
y_val_pred_forward = base_estimator3.predict(X_val[forward_features])
val_rmse_forward = np.sqrt(mean_squared_error(y_val, y_val_pred_forward))

print("Validation RMSE (Forward SFS):", val_rmse_forward)

Forward Selected Features:
['year', 'mileage', 'mpg', 'engineSize', 'engineEfficiency', 'brand_encoded', 'Transmission_Manual', 'Fuel_Petrol']
Validation RMSE (Forward SFS): 4491.302906588517


C:\Users\nicol\anaconda3\envs\Fall2526\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [196]:
sfs_backward = SequentialFeatureSelector(
    estimator=base_estimator3,
    n_features_to_select="auto",
    direction="backward",
    scoring="neg_mean_squared_error",
    cv=5,
    n_jobs=-1
)

sfs_backward.fit(X_train, y_train)

# Selected feature mask and names
backward_mask = sfs_backward.get_support()
backward_features = X_train.columns[backward_mask]

print("Backward Selected Features:")
print(list(backward_features))

# Evaluate on validation set
base_estimator3.fit(X_train[backward_features], y_train)
y_val_pred_backward = base_estimator3.predict(X_val[backward_features])
val_rmse_backward = np.sqrt(mean_squared_error(y_val, y_val_pred_backward))

print("Validation RMSE (Backward SFS):", val_rmse_backward)

Backward Selected Features:
['year', 'mileage', 'mpg', 'engineSize', 'brand_encoded', 'Transmission_Manual', 'Fuel_Hybrid', 'Fuel_Petrol']
Validation RMSE (Backward SFS): 4489.787920247805


C:\Users\nicol\anaconda3\envs\Fall2526\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
